SET(CTEST_PROJECT_NAME JustKernels)
SET(CTEST_NIGHTLY_START_TIME "00:00:00 EST")
SET(CTEST_DROP_SITE_CDASH TRUE)

IF(NOT $ENV{CTEST_DROP_METHOD} STREQUAL "")
  SET(CTEST_DROP_METHOD $ENV{CTEST_DROP_METHOD})
ENDIF()

IF(NOT DEFINED CTEST_DROP_METHOD)
  SET(CTEST_DROP_METHOD "http")
ENDIF(NOT DEFINED CTEST_DROP_METHOD)

IF(CTEST_DROP_METHOD STREQUAL "http")
  SET(CTEST_DROP_SITE "my.cdash.org")
  SET(CTEST_DROP_LOCATION "/submit.php?project=JustKernels")
ENDIF(CTEST_DROP_METHOD STREQUAL "http")
  
