#!/bin/bash --login

install_location=$1
branch=$2
#conda_exe=$(which conda)
#export CEESD_CONDA_PREFIX="$(dirname ${conda_exe})"/.. 
if [ -z "${branch}" ]; then branch="master"; fi
if [ ! -d ${install_location} ]
then
    mkdir -p ${install_location}
fi
branchname_safe=`printf "${branch}" | sed 's/\//_/g'`
#mcinstall_loc=${install_location}/mirgecom-${branchname_safe}-install
#eminstall_loc=${install_location}/emirge-mc-${branchname_safe}-install
#rm -rf ${mcinstall_loc}
if [ -d "${install_location}/mirgecom" ]
then    
    cd ${install_location}/mirgecom && git checkout ${branch} && git pull
else
    git clone -b ${branch} git@github.com:/illinois-ceesd/mirgecom ${install_location}/mirgecom 
fi
#git clone git@github.com:/illinois-ceesd/emirge ${eminstall_loc}
#git clone -b ${branch} git@github.com:/illinois-ceesd/mirgecom ${mcinstall_loc}
#cd ${mcinstall_loc} && python setup.py develop
#cd ${install_location}/emirge
#./install.sh --conda-prefix=${CEESD_CONDA_PREFIX} --env-name=abate.${branchname_safe}.env --install-prefix=${install_location}/miregcom-${branchname_safe}-install
#printf "Cloning mirgecom(${branch}) to (${install_location})...\n"
#git clone -b ${branch} git@github.com:/illinois-ceesd/mirgecom ${install_location}/mirgecom
#cd ${install_location}
#python setup.py develop
