#!/bin/bash

install_location=$1
branch=$2
export CEESD_CONDA_PREFIX=/g/g17/mtcampbe/ceesd/Lassen/conda-install
if [ -z "${branch}" ]; then branch="master"; fi
if [ ! -d ${install_location} ]
then
    mkdir -p ${install_location}
fi
branchname_safe=`printf "${branch}" | sed 's/\//_/g'`
cd mirgecom && git checkout ${branch} && git pull
git clone git@github.com:/illinois-ceesd/emirge ${install_location}/emirge
cd ${install_location}/emirge
./install.sh --conda-prefix=${CEESD_CONDA_PREFIX} --env-name=abate.${branchname_safe}.env --install-prefix=${install_location}/miregcom-${branchname_safe}-install
#printf "Cloning mirgecom(${branch}) to (${install_location})...\n"
#git clone -b ${branch} git@github.com:/illinois-ceesd/mirgecom ${install_location}/mirgecom
#cd ${install_location}
#python setup.py develop
