.TH "citelist" 3 "Fri Apr 10 2020" "Version 1.0" "JustKernels" \" -*- nroff -*-
.ad l
.nh
.SH NAME
citelist \- Bibliography 

.IP "\fB[1]\fP" 1c
A\&. J\&. Christlieb, J\&. A\&. Rossmanith, and Q\&. Tang\&. A high-order WENO finite difference scheme for the equations of ideal magnetohydrodynamics\&. \fIJournal of Computational Physics\fP, 268:302--325, 2014\&.
.PP
.IP "\fB[2]\fP" 1c
G\&. S\&. Jiang and C\&. W\&. Shu\&. Efficient Implementation of Weighted ENO Schemes\&. \fIJournal of Computational Physics\fP, 126(1):202--228, 1996\&.
.PP
.IP "\fB[3]\fP" 1c
G\&. Jiang and C\&. Wu\&. A high-order weno finite difference scheme for the equations of ideal magnetohydrodynamics\&. \fIJournal of Computational Physics\fP, 150(2):561--594, 1999\&.
.PP
.IP "\fB[4]\fP" 1c
G\&. S\&. Jiang and C\&. C\&. Wu\&. A high-order WENO finite difference scheme for the equations of ideal magnetohydrodynamics\&. \fIJournal of Computational Physics\fP, 150(2):561--594, 1999\&.
.PP
.IP "\fB[5]\fP" 1c
J\&. W\&. Kim and D\&. J\&. Lee\&. Generalized characteristic boundary conditions for computational aeroacoustics, part 2\&. \fIAIAA journal\fP, 42(1):47--55, 2004\&.
.PP
.IP "\fB[6]\fP" 1c
S\&. K\&. Lele\&. Compact Finite Difference Schemes with Spectral-like Resolution\&. \fIJ\&. Comp\&. Phys\&.\fP, 103:16--42, 1992\&.
.PP
.IP "\fB[7]\fP" 1c
T\&. Nonomura and K\&. Fujii\&. Characteristic finite-difference weno scheme for multicomponent compressible fluid analysis: Overestimated quasi-conservative formulation maintaining equilibriums of velocity, pressure, and temperature\&. \fIJournal of Computational Physics\fP, 340:358--388, 2017\&.
.PP
.IP "\fB[8]\fP" 1c
Taku Nonomura, Daiki Terakado, Yoshiaki Abe, and Kozo Fujii\&. A new technique for freestream preservation of finite-difference weno on curvilinear grid\&. \fIComputers & Fluids\fP, 107:242--255, 2015\&.
.PP
.IP "\fB[9]\fP" 1c
J\&. Shuen, M\&. Liou, and B\&. Van Leer\&. Inviscid flux-splitting algorithms for real gases with non-equilibrium chemistry\&. \fIJournal of Computational Physics\fP, 90(2):371--395, 1990\&.
.PP
.IP "\fB[10]\fP" 1c
J\&. Shuen\&. Upwind differencing and LU factorization for chemical non-equilibrium Navier-Stokes equations\&. \fIJournal of Computational Physics\fP, 99(2):233--250, 1992\&.
.PP
.IP "\fB[11]\fP" 1c
M\&. Vinokur\&. Conservation equations of gasdynamics in curvilinear coordinate systems\&. \fIJ\&. Comp\&. Phys\&.\fP, 14:105--125, 1974\&.
.PP
.IP "\fB[12]\fP" 1c
M\&. R\&. Visbal and D\&. V\&. Gaitonde\&. On the Use of Higher-Order Finite-Difference Schemes on Curvilinear and Deforming Meshes\&. \fIJournal of Computational Physics\fP, 181:155--185, 2002\&.
.PP
.PP

