euler
NAME
euler -
SYNOPSIS
Functions/Subroutines
subroutine flux1d (numDim, numPoints, gridSizes, opInterval, fluxDir, gridType, gridMetric, rhoBuffer, rhoVBuffer, rhoEBuffer, velHat, pressureBuffer, fluxBuffer)
Computes the inviscid fluxes in one dimension.
subroutine scalarflux1d (numDim, numPoints, gridSizes, opInterval, numScalars, scalarBuffer, velHat, fluxBuffer)
Flux for scalar transport.
Function/Subroutine Documentation
subroutine euler::flux1d (integer(kind=4), intent(in) numDim, integer(kind=8), intent(in) numPoints, integer(kind=8), dimension(numdim), intent(in) gridSizes, integer(kind=8), dimension(2*numdim), intent(in) opInterval, integer(kind=4), intent(in) fluxDir, integer(kind=4), intent(in) gridType, real(kind=8), dimension(numdim*numdim*numpoints), intent(in), target gridMetric, real(kind=8), dimension(numpoints), intent(in) rhoBuffer, real(kind=8), dimension(numdim*numpoints), intent(in), target rhoVBuffer, real(kind=8), dimension(numpoints), intent(in) rhoEBuffer, real(kind=8), dimension(numpoints), intent(in) velHat, real(kind=8), dimension(numpoints), intent(in) pressureBuffer, real(kind=8), dimension(numpoints*(numdim+2)), intent(out), target fluxBuffer)
Computes the inviscid fluxes in one dimension. This routine computes the inviscid fluxes of the single gas NS in one dimension. For example in the $\hat{\xi}$ direction, the inviscid flux is: \[ \hat{\vec{F}}^I_1 = \begin{bmatrix} \rho \hat{U} \ \rho u \hat{U} + p\hat{\xi}_x \ \rho v \hat{U} + p \hat{\xi}_y \ \rho w \hat{U} + p\hat{\xi}_z \ (\rho E + p)\hat{U} - \hat{\xi}_t p \nd{bmatrix}, \]
Parameters:
numDim - const integer indicating number of dimensions
numPoints - const 64-bit integer indicating total size of input arrays
gridSizes - const 64-bit integer 1d array of size numDim, which indicates the number of points in each dimension for the grid
opInterval - const 64-bit integer 1d array of size 2 x numDim which indicates the rectangular interval over which this routine should operate. e.g. [iStart iEnd jStart jEnd ... ]
fluxDir - const integer indicating the direction in which the flux is to be calculated
gridType - const integer indicating whether the gridMetric parameter is a Cartesian, Rectilinear, or Curvilinear metric
gridMetric - const double precision 1d array containing the grid metric
rhoBuffer - ( $\rho$) const double precision contiguous 1d array of size numPoints representing the density at each point on the grid
rhoVBuffer - ( $\rho\vec{V}$) const double precision contiguous 1d array of size numDim x numPoints representing the momentum density at each point on the grid.
rhoEBuffer - ( $\rho E$) const double precision contiguous 1d array of size numPoints representing the energy density at each point on the grid
velHat - ( $\hat{U}$) - const double precision contiguous 1d array of size numPoints representing the component of the contravariant velocity corresponding to the direction (fluxDir) in which the fluxes are to be calculated
pressureBuffer - (p) - const double precision contiguous 1d array of size numPoints representing the pressure at each point on the grid
fluxBuffer - double precision contiguous 1d array of size (numDim + 2) x numPoints for output of the fluxes for each equation. The fluxBuffer is returned with (numDim + 2) blocks of size numPoints, one block for each equation.
Definition at line 38 of file Euler.f90.
References grid::curvilinear, grid::rectilinear, simple::zawpxy(), simple::zvwpxy(), simple::zwmxpy(), and simple::zxy().
subroutine euler::scalarflux1d (integer(kind=4), intent(in) numDim, integer(kind=8), intent(in) numPoints, integer(kind=8), dimension(numdim), intent(in) gridSizes, integer(kind=8), dimension(2*numdim), intent(in) opInterval, integer(kind=4), intent(in) numScalars, real(kind=8), dimension(numscalars*numpoints), intent(in), target scalarBuffer, real(kind=8), dimension(numpoints), intent(in) velHat, real(kind=8), dimension(numscalars*numpoints), intent(out), target fluxBuffer)
Flux for scalar transport.
Definition at line 152 of file Euler.f90.
References simple::zxy().
Author
Generated automatically by Doxygen for JustKernels from the source code.