.TH "Euler.f90" 3 "Fri Apr 10 2020" "Version 1.0" "JustKernels" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Euler.f90 \- 
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBeuler\fP"
.br
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBflux1d\fP (\fBnumDim\fP, \fBnumPoints\fP, \fBgridSizes\fP, \fBopInterval\fP, \fBfluxDir\fP, \fBgridType\fP, \fBgridMetric\fP, \fBrhoBuffer\fP, \fBrhoVBuffer\fP, \fBrhoEBuffer\fP, \fBvelHat\fP, \fBpressureBuffer\fP, \fBfluxBuffer\fP)"
.br
.RI "Computes the inviscid fluxes in one dimension\&. "
.ti -1c
.RI "subroutine \fBscalarflux1d\fP (\fBnumDim\fP, \fBnumPoints\fP, \fBgridSizes\fP, \fBopInterval\fP, \fBnumScalars\fP, \fBscalarBuffer\fP, \fBvelHat\fP, \fBfluxBuffer\fP)"
.br
.RI "Flux for scalar transport\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JustKernels from the source code\&.
