grid
NAME
grid -
SYNOPSIS
Functions/Subroutines
subroutine computegridmetrics (numDim, gridSizes, numPoints, opInterval, numStencils, numStencilValues, stencilSizes, stencilStarts, stencilOffsets, stencilWeights, stencilID, gridCoordinates, gridMetricTensor, gridJacobianDeterminants)
subroutine computecurvilineargridmetrics (numDim, gridSizes, numPoints, opInterval, numStencils, numStencilValues, stencilSizes, stencilStarts, stencilOffsets, stencilWeights, stencilID, gridCoordinates, gridMetricTensor, gridJacobianDeterminants)
subroutine applyuniformgridmetric (numDim, gridSizes, numPoints, opInterval, gridMetric, vBuffer, vHat)
subroutine applycartesiangridmetric (numDim, gridSizes, numPoints, opInterval, gridMetric, vBuffer, vHat)
Variables
integer(kind=4), parameter cartesian = 0
integer(kind=4), parameter unirect = 1
integer(kind=4), parameter rectilinear = 2
integer(kind=4), parameter curvilinear = 3
Function/Subroutine Documentation
subroutine grid::applycartesiangridmetric (integer(kind=4), intent(in) numDim, integer(kind=8), dimension(numdim), intent(in) gridSizes, integer(kind=8), intent(in) numPoints, integer(kind=8), dimension(2*numdim), intent(in) opInterval, real(kind=8), dimension(numdim*numpoints), intent(in) gridMetric, real(kind=8), dimension(numdim*numpoints), intent(in) vBuffer, real(kind=8), dimension(numdim*numpoints), intent(out) vHat)
Definition at line 255 of file Grid.f90.
subroutine grid::applyuniformgridmetric (integer(kind=4), intent(in) numDim, integer(kind=8), dimension(numdim), intent(in) gridSizes, integer(kind=8), intent(in) numPoints, integer(kind=8), dimension(2*numdim), intent(in) opInterval, real(kind=8), dimension(numdim), intent(in) gridMetric, real(kind=8), dimension(numdim*numpoints), intent(in) vBuffer, real(kind=8), dimension(numdim*numpoints), intent(out) vHat)
Definition at line 172 of file Grid.f90.
subroutine grid::computecurvilineargridmetrics (integer(kind=4), intent(in) numDim, integer(kind=8), dimension(numdim), intent(in) gridSizes, integer(kind=8), intent(in) numPoints, integer(kind=8), dimension(2*numdim), intent(in) opInterval, integer(kind=4), intent(in) numStencils, integer(kind=4), intent(in) numStencilValues, integer(kind=4), dimension(numstencils), intent(in) stencilSizes, integer(kind=4), dimension(numstencils), intent(in) stencilStarts, integer(kind=4), dimension(numstencilvalues), intent(in) stencilOffsets, real(kind=8), dimension(numstencilvalues), intent(in) stencilWeights, integer(kind=4), dimension(numdim*numpoints), intent(in), target stencilID, real(kind=8), dimension(numdim*numpoints), intent(in), target gridCoordinates, real(kind=8), dimension(numdim*numdim*numpoints), intent(inout), target gridMetricTensor, real(kind=8), dimension(2*numpoints), intent(inout), target gridJacobianDeterminants)
Definition at line 57 of file Grid.f90.
References operators::applyoperator(), simple::assignmentxa(), simple::assignmentyx(), and simple::yaxm1().
subroutine grid::computegridmetrics (integer(kind=4), intent(in) numDim, integer(kind=8), dimension(numdim), intent(in) gridSizes, integer(kind=8), intent(in) numPoints, integer(kind=8), dimension(2*numdim), intent(in) opInterval, integer(kind=4), intent(in) numStencils, integer(kind=4), intent(in) numStencilValues, integer(kind=4), dimension(numstencils), intent(in) stencilSizes, integer(kind=4), dimension(numstencils), intent(in) stencilStarts, integer(kind=4), dimension(numstencilvalues), intent(in) stencilOffsets, real(kind=8), dimension(numstencilvalues), intent(in) stencilWeights, integer(kind=4), dimension(numdim*numpoints), intent(in), target stencilID, real(kind=8), dimension(numdim*numpoints), intent(in), target gridCoordinates, real(kind=8), dimension(numdim*numdim*numpoints), intent(inout), target gridMetricTensor, real(kind=8), dimension(2*numpoints), intent(inout), target gridJacobianDeterminants)
Definition at line 20 of file Grid.f90.
Variable Documentation
integer(kind=4), parameter cartesian = 0
Definition at line 5 of file Grid.f90.
integer(kind=4), parameter curvilinear = 3
Definition at line 8 of file Grid.f90.
Referenced by metricops::boundarypointmetric(), euler::flux1d(), and metricops::getpointmetric().
integer(kind=4), parameter rectilinear = 2
Definition at line 7 of file Grid.f90.
Referenced by metricops::alphaweight(), metricops::alphaweight2(), metricops::boundarypointmetric(), satutil::farfield(), euler::flux1d(), metricops::getpointmetric(), metricops::gradijktogradxyz(), metricops::ijkgradtoxyzdiv(), satutil::noslip_isothermal(), viscid::scalarflux1d(), satutil::slip_adiabatic(), viscid::strongflux1d(), and metricops::vhatcomponent().
integer(kind=4), parameter unirect = 1
Definition at line 6 of file Grid.f90.
Author
Generated automatically by Doxygen for JustKernels from the source code.