.TH "MetricOps.f90" 3 "Fri Apr 10 2020" "Version 1.0" "JustKernels" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MetricOps.f90 \- 
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBmetricops\fP"
.br
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBalphaweight\fP (\fBnumDim\fP, \fBnumPointsBuffer\fP, \fBbufferSizes\fP, \fBopInterval\fP, \fBgridType\fP, \fBgridMetric\fP, \fBalphaDir\fP, alphaW)"
.br
.ti -1c
.RI "subroutine \fBalphaweight2\fP (\fBnumDim\fP, \fBnumPointsBuffer\fP, \fBbufferSizes\fP, \fBopInterval\fP, \fBgridType\fP, \fBgridMetric\fP, \fBgridJacobian\fP, \fBalphaDir\fP, alphaW)"
.br
.ti -1c
.RI "subroutine \fBvhatcomponent\fP (\fBnumDim\fP, \fBnumPointsBuffer\fP, \fBbufferSizes\fP, \fBopInterval\fP, \fBgridType\fP, \fBgridMetric\fP, \fBvelDir\fP, \fBvelocity\fP, velHatComponent)"
.br
.ti -1c
.RI "subroutine \fBijkgradtoxyzdiv\fP (\fBnumDim\fP, \fBnumPoints\fP, \fBgridSizes\fP, \fBopInterval\fP, \fBgridType\fP, \fBgridJacobian\fP, \fBgridMetric\fP, \fBgradVBuffer\fP, \fBdivBuffer\fP)"
.br
.ti -1c
.RI "subroutine \fBgradijktogradxyz\fP (\fBnumDim\fP, \fBnumPoints\fP, \fBgridSizes\fP, \fBopInterval\fP, \fBgridType\fP, \fBgridJacobian\fP, \fBgridMetric\fP, \fBgradIJK\fP, \fBgradXYZ\fP)"
.br
.RI "Converts Cartesian (computational) gradient to physical coordinates\&. "
.ti -1c
.RI "subroutine \fBgetpointmetric\fP (\fBnumDim\fP, \fBnumPointsBuffer\fP, \fBpointID\fP, \fBgridType\fP, \fBgridMetric\fP, \fBpointMetric\fP)"
.br
.ti -1c
.RI "subroutine \fBboundarypointmetric\fP (\fBnumDim\fP, \fBnormDir\fP, \fBnumPointsBuffer\fP, \fBpointID\fP, \fBgridType\fP, \fBgridMetric\fP, \fBpointMetric\fP)"
.br
.ti -1c
.RI "subroutine \fBpointeigenvectors\fP (\fBnumDim\fP, \fBpointMetric\fP, \fBeigenVectors\fP, \fBmetricMags\fP)"
.br
.ti -1c
.RI "real(kind=8) function \fBvdot\fP (\fBnumDim\fP, u, v)"
.br
.ti -1c
.RI "subroutine \fBpointeigenvectorsgs\fP (\fBnumDim\fP, \fBpointMetric\fP, \fBeigenVectors\fP, \fBeigenComponents\fP)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JustKernels from the source code\&.
