metricops
NAME
metricops -
SYNOPSIS
Functions/Subroutines
subroutine alphaweight (numDim, numPointsBuffer, bufferSizes, opInterval, gridType, gridMetric, alphaDir, alphaW)
subroutine alphaweight2 (numDim, numPointsBuffer, bufferSizes, opInterval, gridType, gridMetric, gridJacobian, alphaDir, alphaW)
subroutine vhatcomponent (numDim, numPointsBuffer, bufferSizes, opInterval, gridType, gridMetric, velDir, velocity, velHatComponent)
subroutine ijkgradtoxyzdiv (numDim, numPoints, gridSizes, opInterval, gridType, gridJacobian, gridMetric, gradVBuffer, divBuffer)
subroutine gradijktogradxyz (numDim, numPoints, gridSizes, opInterval, gridType, gridJacobian, gridMetric, gradIJK, gradXYZ)
Converts Cartesian (computational) gradient to physical coordinates.
subroutine getpointmetric (numDim, numPointsBuffer, pointID, gridType, gridMetric, pointMetric)
subroutine boundarypointmetric (numDim, normDir, numPointsBuffer, pointID, gridType, gridMetric, pointMetric)
subroutine pointeigenvectors (numDim, pointMetric, eigenVectors, metricMags)
real(kind=8) function vdot (numDim, u, v)
subroutine pointeigenvectorsgs (numDim, pointMetric, eigenVectors, eigenComponents)
Function/Subroutine Documentation
subroutine metricops::alphaweight (integer(kind=4), intent(in) numDim, integer(kind=8), intent(in) numPointsBuffer, integer(kind=8), dimension(numdim), intent(in) bufferSizes, integer(kind=8), dimension(2*numdim), intent(in) opInterval, integer(kind=4), intent(in) gridType, real(kind=8), dimension(numdim*numdim*numpointsbuffer), intent(in), target gridMetric, integer(kind=4), intent(in) alphaDir, real(kind=8), dimension(numpointsbuffer), intent(out) alphaW)
Definition at line 15 of file MetricOps.f90.
References simple::assignmentxa(), simple::assignmentyabsx(), grid::rectilinear, and simple::veclen().
subroutine metricops::alphaweight2 (integer(kind=4), intent(in) numDim, integer(kind=8), intent(in) numPointsBuffer, integer(kind=8), dimension(numdim), intent(in) bufferSizes, integer(kind=8), dimension(2*numdim), intent(in) opInterval, integer(kind=4), intent(in) gridType, real(kind=8), dimension(numdim*numdim*numpointsbuffer), intent(in), target gridMetric, real(kind=8), dimension(numpointsbuffer), intent(in), target gridJacobian, integer(kind=4), intent(in) alphaDir, real(kind=8), dimension(numpointsbuffer), intent(out) alphaW)
Definition at line 60 of file MetricOps.f90.
References simple::assignmentxa(), simple::assignmentyabsx(), grid::rectilinear, simple::veclen(), and simple::yxy().
subroutine metricops::boundarypointmetric (integer(kind=4), intent(in) numDim, integer(kind=4), intent(in) normDir, integer(kind=8), intent(in) numPointsBuffer, integer(kind=8), intent(in) pointID, integer(kind=4), intent(in) gridType, real(kind=8), dimension(numdim*numdim*numpointsbuffer), intent(in) gridMetric, real(kind=8), dimension(numdim*numdim), intent(out) pointMetric)
Definition at line 353 of file MetricOps.f90.
References grid::curvilinear, and grid::rectilinear.
Referenced by satutil::farfield(), satutil::noslip_isothermal(), and satutil::slip_adiabatic().
subroutine metricops::getpointmetric (integer(kind=4), intent(in) numDim, integer(kind=8), intent(in) numPointsBuffer, integer(kind=8), intent(in) pointID, integer(kind=4), intent(in) gridType, real(kind=8), dimension(numdim*numdim*numpointsbuffer), intent(in) gridMetric, real(kind=8), dimension(numdim*numdim), intent(out) pointMetric)
Definition at line 313 of file MetricOps.f90.
References grid::curvilinear, and grid::rectilinear.
subroutine metricops::gradijktogradxyz (integer(kind=4), intent(in) numDim, integer(kind=8), intent(in) numPoints, integer(kind=8), dimension(numdim), intent(in) gridSizes, integer(kind=8), dimension(2*numdim), intent(in) opInterval, integer(kind=4), intent(in) gridType, real(kind=8), dimension(numpoints), intent(in) gridJacobian, real(kind=8), dimension(numdim*numdim*numpoints), intent(in), target gridMetric, real(kind=8), dimension(numdim*numpoints), intent(in), target gradIJK, real(kind=8), dimension(numdim*numpoints), intent(out), target gradXYZ)
Converts Cartesian (computational) gradient to physical coordinates.
Definition at line 240 of file MetricOps.f90.
References simple::assignmentxa(), grid::rectilinear, simple::yax(), simple::ywxpy(), simple::yxy(), and simple::zxy().
subroutine metricops::ijkgradtoxyzdiv (integer(kind=4), intent(in) numDim, integer(kind=8), intent(in) numPoints, integer(kind=8), dimension(numdim), intent(in) gridSizes, integer(kind=8), dimension(2*numdim), intent(in) opInterval, integer(kind=4), intent(in) gridType, real(kind=8), dimension(numpoints), intent(in) gridJacobian, real(kind=8), dimension(numdim*numdim*numpoints), intent(in), target gridMetric, real(kind=8), dimension(numdim*numdim*numpoints), intent(in), target gradVBuffer, real(kind=8), dimension(numpoints), intent(out) divBuffer)
Definition at line 182 of file MetricOps.f90.
References grid::rectilinear, simple::xax(), simple::yaxpy(), simple::ywxpy(), and simple::yxy().
subroutine metricops::pointeigenvectors (integer(kind=4), intent(in) numDim, real(kind=8), dimension(numdim*numdim), intent(in) pointMetric, real(kind=8), dimension(numdim*numdim), intent(out) eigenVectors, real(kind=8), dimension(numdim), intent(out) metricMags)
Definition at line 406 of file MetricOps.f90.
Referenced by satutil::farfield(), satutil::noslip_isothermal(), and satutil::slip_adiabatic().
subroutine metricops::pointeigenvectorsgs (integer(kind=4), intent(in) numDim, real(kind=8), dimension(numdim*numdim), intent(in) pointMetric, real(kind=8), dimension(numdim*numdim), intent(out) eigenVectors, real(kind=8), dimension(numdim*numdim), intent(out) eigenComponents)
Definition at line 453 of file MetricOps.f90.
References vdot().
Referenced by roe::eigenmatrices().
real(kind=8) function metricops::vdot (integer(kind=4), intent(in) numDim, real(kind=8), dimension(numdim), intent(in) u, real(kind=8), dimension(numdim), intent(in) v)
Definition at line 433 of file MetricOps.f90.
Referenced by pointeigenvectorsgs().
subroutine metricops::vhatcomponent (integer(kind=4), intent(in) numDim, integer(kind=8), intent(in) numPointsBuffer, integer(kind=8), dimension(numdim), intent(in) bufferSizes, integer(kind=8), dimension(2*numdim), intent(in) opInterval, integer(kind=4), intent(in) gridType, real(kind=8), dimension(numdim*numdim*numpointsbuffer), intent(in), target gridMetric, integer(kind=4), intent(in) velDir, real(kind=8), dimension(numdim*numpointsbuffer), intent(in), target velocity, real(kind=8), dimension(numpointsbuffer), intent(out) velHatComponent)
Definition at line 112 of file MetricOps.f90.
References grid::rectilinear, simple::yax(), simple::zxdoty(), and simple::zxy().
Author
Generated automatically by Doxygen for JustKernels from the source code.