.TH "dissipation_local" 3 "Fri Apr 10 2020" "Version 1.0" "JustKernels" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dissipation_local \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "real(kind=8), dimension(:,:), allocatable \fBcv_stencil\fP"
.br
.ti -1c
.RI "real(kind=8), dimension(:,:), allocatable \fBf_stencil\fP"
.br
.ti -1c
.RI "real(kind=8), dimension(:,:), allocatable \fBws_stencil\fP"
.br
.ti -1c
.RI "real(kind=8), dimension(:), allocatable \fBws_max_local\fP"
.br
.ti -1c
.RI "real(kind=8), dimension(:,:), allocatable \fBf_stencil_char\fP"
.br
.ti -1c
.RI "real(kind=8), dimension(:,:), allocatable \fBcv_stencil_char\fP"
.br
.ti -1c
.RI "real(kind=8), dimension(:,:), allocatable \fBf_stencil_char_pos\fP"
.br
.ti -1c
.RI "real(kind=8), dimension(:,:), allocatable \fBf_stencil_char_neg\fP"
.br
.ti -1c
.RI "real(kind=8), dimension(:), allocatable \fBf_face_1d_char\fP"
.br
.ti -1c
.RI "real(kind=8), dimension(:), allocatable \fBf_face_1d_char_pos\fP"
.br
.ti -1c
.RI "real(kind=8), dimension(:), allocatable \fBf_face_1d_char_neg\fP"
.br
.ti -1c
.RI "real(kind=8), dimension(:), allocatable \fBul\fP"
.br
.ti -1c
.RI "real(kind=8), dimension(:), allocatable \fBur\fP"
.br
.ti -1c
.RI "real(kind=8), dimension(:,:), allocatable \fBtmat\fP"
.br
.ti -1c
.RI "real(kind=8), dimension(:,:), allocatable \fBtinv\fP"
.br
.ti -1c
.RI "real(kind=8), dimension(:,:), allocatable \fBlambda\fP"
.br
.ti -1c
.RI "real(kind=8), dimension(:), allocatable \fBdvl\fP"
.br
.ti -1c
.RI "real(kind=8), dimension(:), allocatable \fBdvr\fP"
.br
.ti -1c
.RI "real(kind=8), dimension(:), allocatable \fBuroe\fP"
.br
.ti -1c
.RI "real(kind=8), dimension(:), allocatable \fBdvroe\fP"
.br
.ti -1c
.RI "real(kind=8), dimension(:), allocatable \fBdproe\fP"
.br
.ti -1c
.RI "real(kind=8), dimension(:), allocatable \fBpointmetricr\fP"
.br
.ti -1c
.RI "real(kind=8), dimension(:), allocatable \fBpointmetricl\fP"
.br
.ti -1c
.RI "real(kind=8), dimension(:), allocatable \fBpointmetric\fP"
.br
.ti -1c
.RI "real(kind=8), dimension(:), allocatable \fBmetricunitvectors\fP"
.br
.ti -1c
.RI "real(kind=8), dimension(:), allocatable \fBmetricmags\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 31 of file NavierStokesRHSWENO\&.f90\&.
.SH "Member Data Documentation"
.PP 
.SS "real(kind=8), dimension(:,:), allocatable cv_stencil"

.PP
Definition at line 32 of file NavierStokesRHSWENO\&.f90\&.
.SS "real(kind=8), dimension(:,:), allocatable cv_stencil_char"

.PP
Definition at line 37 of file NavierStokesRHSWENO\&.f90\&.
.SS "real(kind=8), dimension(:), allocatable dproe"

.PP
Definition at line 52 of file NavierStokesRHSWENO\&.f90\&.
.SS "real(kind=8), dimension(:), allocatable dvl"

.PP
Definition at line 48 of file NavierStokesRHSWENO\&.f90\&.
.SS "real(kind=8), dimension(:), allocatable dvr"

.PP
Definition at line 49 of file NavierStokesRHSWENO\&.f90\&.
.SS "real(kind=8), dimension(:), allocatable dvroe"

.PP
Definition at line 51 of file NavierStokesRHSWENO\&.f90\&.
.SS "real(kind=8), dimension(:), allocatable f_face_1d_char"

.PP
Definition at line 40 of file NavierStokesRHSWENO\&.f90\&.
.SS "real(kind=8), dimension(:), allocatable f_face_1d_char_neg"

.PP
Definition at line 42 of file NavierStokesRHSWENO\&.f90\&.
.SS "real(kind=8), dimension(:), allocatable f_face_1d_char_pos"

.PP
Definition at line 41 of file NavierStokesRHSWENO\&.f90\&.
.SS "real(kind=8), dimension(:,:), allocatable f_stencil"

.PP
Definition at line 33 of file NavierStokesRHSWENO\&.f90\&.
.SS "real(kind=8), dimension(:,:), allocatable f_stencil_char"

.PP
Definition at line 36 of file NavierStokesRHSWENO\&.f90\&.
.SS "real(kind=8), dimension(:,:), allocatable f_stencil_char_neg"

.PP
Definition at line 39 of file NavierStokesRHSWENO\&.f90\&.
.SS "real(kind=8), dimension(:,:), allocatable f_stencil_char_pos"

.PP
Definition at line 38 of file NavierStokesRHSWENO\&.f90\&.
.SS "real(kind=8), dimension(:,:), allocatable lambda"

.PP
Definition at line 47 of file NavierStokesRHSWENO\&.f90\&.
.SS "real(kind=8), dimension(:), allocatable metricmags"

.PP
Definition at line 57 of file NavierStokesRHSWENO\&.f90\&.
.SS "real(kind=8), dimension(:), allocatable metricunitvectors"

.PP
Definition at line 56 of file NavierStokesRHSWENO\&.f90\&.
.SS "real(kind=8), dimension(:), allocatable pointmetric"

.PP
Definition at line 55 of file NavierStokesRHSWENO\&.f90\&.
.SS "real(kind=8), dimension(:), allocatable pointmetricl"

.PP
Definition at line 54 of file NavierStokesRHSWENO\&.f90\&.
.SS "real(kind=8), dimension(:), allocatable pointmetricr"

.PP
Definition at line 53 of file NavierStokesRHSWENO\&.f90\&.
.SS "real(kind=8), dimension(:,:), allocatable tinv"

.PP
Definition at line 46 of file NavierStokesRHSWENO\&.f90\&.
.SS "real(kind=8), dimension(:,:), allocatable tmat"

.PP
Definition at line 45 of file NavierStokesRHSWENO\&.f90\&.
.SS "real(kind=8), dimension(:), allocatable ul"

.PP
Definition at line 43 of file NavierStokesRHSWENO\&.f90\&.
.SS "real(kind=8), dimension(:), allocatable ur"

.PP
Definition at line 44 of file NavierStokesRHSWENO\&.f90\&.
.SS "real(kind=8), dimension(:), allocatable uroe"

.PP
Definition at line 50 of file NavierStokesRHSWENO\&.f90\&.
.SS "real(kind=8), dimension(:), allocatable ws_max_local"

.PP
Definition at line 35 of file NavierStokesRHSWENO\&.f90\&.
.SS "real(kind=8), dimension(:,:), allocatable ws_stencil"

.PP
Definition at line 34 of file NavierStokesRHSWENO\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for JustKernels from the source code\&.
