.TH "NavierStokesRHSWENO.f90" 3 "Fri Apr 10 2020" "Version 1.0" "JustKernels" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NavierStokesRHSWENO.f90 \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Types"

.in +1c
.ti -1c
.RI "type \fBdissipation_local\fP"
.br
.ti -1c
.RI "type \fBcharacteristic_local\fP"
.br
.ti -1c
.RI "type \fBupwinding_local\fP"
.br
.in -1c
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBnavierstokesrhsweno\fP"
.br
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBallocate_local_types\fP (d_local, c_local, u_local, \fBnumEquations\fP, \fBnumDim\fP, nAuxVars)"
.br
.ti -1c
.RI "subroutine \fBallocate_upwinding_local\fP (u_local, \fBnumEquations\fP)"
.br
.ti -1c
.RI "subroutine \fBdeallocate_local_types\fP (d_local, c_local, u_local)"
.br
.ti -1c
.RI "subroutine \fBdeallocate_upwinding_local\fP (u_local)"
.br
.ti -1c
.RI "subroutine \fBns_rhs_weno\fP (\fBnumDim\fP, \fBbufferSizes\fP, \fBnumPointsBuffer\fP, \fBnumScalars\fP, \fBnumEquations\fP, \fBdir\fP, \fBsconn\fP, dfluxbuffer, \fBinviscidFluxBuffer\fP, \fBopInterval\fP, \fBgridMetric\fP, \fBjacobianDeterminant\fP, \fBgridCoordinates\fP, \fBgridType\fP, \fBrhoBuffer\fP, \fBrhoVBuffer\fP, \fBrhoEBuffer\fP, \fBpressureBuffer\fP, \fBtemperatureBuffer\fP, \fBsosBuffer\fP, \fBscalarBuffer\fP, WENO_alpha, \fBwenoOptions\fP, eosGasInfo, \fBeosNonDimen\fP, \fBeosGasParams\fP)"
.br
.ti -1c
.RI "subroutine \fBapply_weno_js_consistent\fP (\fBdir\fP, p_map, smap, \fBinviscidFluxBuffer\fP, f_face_1d, index_weno, \fBnumEquations\fP, \fBnumPointsBuffer\fP, haveAxis, s)"
.br
.ti -1c
.RI "subroutine \fBconserved_variables_single_point\fP (u, \fBrhoBuffer\fP, \fBrhoVBuffer\fP, \fBrhoEBuffer\fP, \fBscalarBuffer\fP, map, smap, \fBnumDim\fP, nauxVars, \fBnumEquations\fP, \fBnumPointsBuffer\fP, haveAxis)"
.br
.ti -1c
.RI "subroutine \fBfrozen_incviscid_flux\fP (f_stencil, width, \fBrhoBuffer\fP, \fBrhoVBuffer\fP, \fBrhoEBuffer\fP, \fBscalarBuffer\fP, \fBpressureBuffer\fP, map, p_map, smap, \fBnumDim\fP, nauxVars, \fBnumEquations\fP, \fBnumPointsBuffer\fP, MT1_freeze, haveAxis)"
.br
.ti -1c
.RI "subroutine \fBcharacteristic_velocity\fP (ws_stencil, width, iLeft, iRight, \fBrhoBuffer\fP, \fBrhoVBuffer\fP, \fBrhoEBuffer\fP, \fBscalarBuffer\fP, \fBpressureBuffer\fP, \fBtemperatureBuffer\fP, \fBsosBuffer\fP, map, p_map, smap, \fBdir\fP, \fBnumDim\fP, nauxVars, \fBnumEquations\fP, \fBnumPointsBuffer\fP, \fBgridMetric\fP, \fBjacobianDeterminant\fP, \fBeosInfo\fP, \fBeosNonDimen\fP, \fBeosGasParams\fP, haveAxis, c_local)"
.br
.ti -1c
.RI "subroutine \fBcomputecharacteristicvelocities\fP (\fBnumDim\fP, \fBnumPointsBuffer\fP, \fBbufferSizes\fP, \fBopInterval\fP, \fBnumEquations\fP, nAuxVars, haveAxis, \fBdir\fP, velocityBuffer, \fBsosBuffer\fP, \fBgridMetric\fP, \fBjacobianDeterminant\fP, charVel)"
.br
.ti -1c
.RI "subroutine \fBcharacteristic_velocity_old\fP (ws_stencil, width, iLeft, iRight, \fBrhoBuffer\fP, \fBrhoVBuffer\fP, \fBrhoEBuffer\fP, \fBscalarBuffer\fP, \fBpressureBuffer\fP, \fBtemperatureBuffer\fP, \fBsosBuffer\fP, map, p_map, smap, \fBdir\fP, \fBnumDim\fP, nauxVars, \fBnumEquations\fP, \fBnumPointsBuffer\fP, \fBgridMetric\fP, \fBjacobianDeterminant\fP, \fBeosInfo\fP, \fBeosNonDimen\fP, \fBeosGasParams\fP, haveAxis)"
.br
.ti -1c
.RI "subroutine \fBapply_weno_js_dissipation\fP (\fBdir\fP, p_map, smap, \fBnumDim\fP, \fBnumEquations\fP, f_face_1d, index_weno, WENO_alpha, nAuxVars, WENO_STRONGSHOCKS, \fBnumPointsBuffer\fP, \fBrhoBuffer\fP, \fBrhoVBuffer\fP, \fBrhoEBuffer\fP, \fBscalarBuffer\fP, \fBpressureBuffer\fP, \fBtemperatureBuffer\fP, \fBsosBuffer\fP, \fBgridMetric\fP, \fBjacobianDeterminant\fP, \fBeosInfo\fP, \fBeosNonDimen\fP, \fBeosGasParams\fP, \fBgridType\fP, haveAxis, d_local, c_local, u_local)"
.br
.ti -1c
.RI "subroutine \fBapply_weno_js_dissipation_old\fP (\fBdir\fP, p_map, smap, \fBnumDim\fP, \fBnumEquations\fP, f_face_1d, index_weno, WENO_alpha, nAuxVars, WENO_STRONGSHOCKS, \fBnumPointsBuffer\fP, \fBrhoBuffer\fP, \fBrhoVBuffer\fP, \fBrhoEBuffer\fP, \fBscalarBuffer\fP, \fBpressureBuffer\fP, \fBtemperatureBuffer\fP, \fBsosBuffer\fP, \fBgridMetric\fP, \fBjacobianDeterminant\fP, \fBeosInfo\fP, \fBeosNonDimen\fP, \fBeosGasParams\fP, \fBgridType\fP, haveAxis)"
.br
.ti -1c
.RI "subroutine \fBdissipation_part_by_upwinding_flux\fP (f_stencil_char_sign, \fBdir\fP, \fBnumDim\fP, \fBnumEquations\fP, width, sign_flag, MT1_freeze, f_face_1d_char, u_local)"
.br
.ti -1c
.RI "subroutine \fBns_rhs_muscl\fP (\fBnumDim\fP, \fBbufferSizes\fP, \fBnumPointsBuffer\fP, \fBnormDir\fP, \fBsconn\fP, \fBopInterval\fP, \fBbufferInterval\fP, \fBgridType\fP, \fBgridMetric\fP, \fBjacobianDeterminant\fP, \fBbcParams\fP, \fBgasParams\fP, \fBnumScalars\fP, \fBrhoBuffer\fP, \fBrhoVBuffer\fP, \fBrhoEBuffer\fP, \fBscalarBuffer\fP, \fBpressureBuffer\fP, \fBtemperatureBuffer\fP, \fBsosBuffer\fP, \fBrhoRHSBuffer\fP, \fBrhoVRHSBuffer\fP, \fBrhoERHSBuffer\fP, \fBscalarRHSBuffer\fP, WENO_alpha, \fBwenoOptions\fP, \fBeosInfo\fP, \fBeosNonDimen\fP, \fBeosGasParams\fP)"
.br
.ti -1c
.RI "subroutine \fBmuscl_reconstruction\fP (f_input, \fBnumEquations\fP, NpencilW, i1, i2, i3, side, f_output)"
.br
.ti -1c
.RI "subroutine \fBinviscidflux\fP (\fBrhoBuffer\fP, \fBrhoVBuffer\fP, \fBrhoEBuffer\fP, \fBpressureBuffer\fP, \fBscalarBuffer\fP, p_map, normdir, \fBnumDim\fP, \fBnumScalars\fP, \fBnumEquations\fP, \fBnumPointsBuffer\fP, \fBgridMetric\fP, Npencil, f_stencil)"
.br
.ti -1c
.RI "subroutine \fBinviscidflux_freeze\fP (\fBrhoBuffer\fP, \fBrhoVBuffer\fP, \fBrhoEBuffer\fP, \fBpressureBuffer\fP, \fBscalarBuffer\fP, p_map, normdir, \fBnumDim\fP, \fBnumScalars\fP, \fBnumEquations\fP, \fBnumPointsBuffer\fP, MT1, Npencil, width, f_stencil)"
.br
.ti -1c
.RI "subroutine \fBns_bc_weno\fP (\fBnumDim\fP, \fBbufferSizes\fP, \fBnumPointsBuffer\fP, normDirIn, \fBopInterval\fP, \fBbufferInterval\fP, \fBgridType\fP, \fBgridMetric\fP, \fBgridJacobian\fP, MT2, \fBbcType\fP, \fBbcParams\fP, gasVars, \fBnumScalars\fP, \fBrhoBuffer\fP, \fBrhoVBuffer\fP, \fBrhoEBuffer\fP, \fBscalarBuffer\fP, \fBpressureBuffer\fP, \fBtemperatureBuffer\fP, \fBsosBuffer\fP, \fBrhoRHSBuffer\fP, \fBrhoVRHSBuffer\fP, \fBrhoERHSBuffer\fP, \fBscalarRHSBuffer\fP, \fBeosInfo\fP, \fBeosNonDimen\fP, \fBeosGasParams\fP)"
.br
.ti -1c
.RI "subroutine \fBns_bc_fixvalue\fP (\fBnumDim\fP, \fBbufferSizes\fP, \fBnumPointsBuffer\fP, normDirIn, \fBnumPatchPointsOp\fP, \fBpatchPointsOp\fP, \fBgridType\fP, \fBgridMetric\fP, \fBgridJacobian\fP, \fBbcType\fP, \fBbcParams\fP, gasVars, \fBnumScalars\fP, \fBpressureBuffer\fP, \fBtemperatureBuffer\fP, \fBsosBuffer\fP, \fBeosInfo\fP, \fBeosNonDimen\fP, \fBeosGasParams\fP, \fBrhoTarget\fP, \fBrhoVTarget\fP, \fBrhoETarget\fP, \fBscalarTarget\fP, \fBrhoBuffer\fP, \fBrhoVBuffer\fP, \fBrhoEBuffer\fP, \fBscalarBuffer\fP)"
.br
.ti -1c
.RI "subroutine \fBcross_product\fP (v1, v2, \fBy\fP)"
.br
.ti -1c
.RI "subroutine \fBns_rhs_axisymmetric\fP (\fBnumDim\fP, \fBbufferSizes\fP, \fBnumPointsBuffer\fP, \fBnumScalars\fP, \fBopInterval\fP, \fBgridCoordinates\fP, \fBrhoBuffer\fP, \fBrhoVBuffer\fP, \fBrhoEBuffer\fP, \fBpressureBuffer\fP, \fBscalarBuffer\fP, \fBrhoRHSBuffer\fP, \fBrhoVRHSBuffer\fP, \fBrhoERHSBuffer\fP, \fBscalarRHSBuffer\fP)"
.br
.ti -1c
.RI "subroutine \fBns_rhs_axisymmetric_axis\fP (\fBnumDim\fP, \fBbufferInterval\fP, \fBnumPointsBuffer\fP, \fBnumScalars\fP, \fBnormDir\fP, \fBopInterval\fP, \fBgridMetric\fP, \fBjacobianDeterminant\fP, \fBgridType\fP, \fBgridCoordinates\fP, \fBrhoBuffer\fP, \fBrhoVBuffer\fP, \fBrhoEBuffer\fP, \fBpressureBuffer\fP, \fBscalarBuffer\fP, \fBrhoRHSBuffer\fP, \fBrhoVRHSBuffer\fP, \fBrhoERHSBuffer\fP, \fBscalarRHSBuffer\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "integer(kind=4), parameter \fBnscbc_noslip_isothermal\fP = 6"
.br
.ti -1c
.RI "integer(kind=4), parameter \fBnscbc_slip_adiabatic\fP = 7"
.br
.ti -1c
.RI "integer(kind=4), parameter \fBnscbc_inflow_supersonic\fP = 8"
.br
.ti -1c
.RI "integer(kind=4), parameter \fBnscbc_inflow_subsonic\fP = 9"
.br
.ti -1c
.RI "integer(kind=4), parameter \fBnscbc_inflow_veltemp\fP = 10"
.br
.ti -1c
.RI "integer(kind=4), parameter \fBnscbc_outflow_nonreflection\fP = 11"
.br
.ti -1c
.RI "integer(kind=4), parameter \fBnscbc_axisymmetry\fP = 12"
.br
.ti -1c
.RI "integer(kind=4), parameter \fBweno_central\fP = 1"
.br
.ti -1c
.RI "integer(kind=4), parameter \fBweno_leftboundary1\fP = 4"
.br
.ti -1c
.RI "integer(kind=4), parameter \fBweno_leftboundary2\fP = 8"
.br
.ti -1c
.RI "integer(kind=4), parameter \fBweno_rightboundary1\fP = 10"
.br
.ti -1c
.RI "integer(kind=4), parameter \fBweno_rightboundary2\fP = 14"
.br
.ti -1c
.RI "integer(kind=4), parameter \fBweno_axisboundary1\fP = 20"
.br
.ti -1c
.RI "integer(kind=4), parameter \fBweno_axisboundary2\fP = 26"
.br
.ti -1c
.RI "integer, parameter \fBns\fP = 3"
.br
.ti -1c
.RI "integer(kind=4), parameter \fBwidth\fP = 6"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JustKernels from the source code\&.
