navierstokesrhsweno
NAME
navierstokesrhsweno -
SYNOPSIS
Data Types
type characteristic_local
type dissipation_local
type upwinding_local
Functions/Subroutines
subroutine allocate_local_types (d_local, c_local, u_local, numEquations, numDim, nAuxVars)
subroutine allocate_upwinding_local (u_local, numEquations)
subroutine deallocate_local_types (d_local, c_local, u_local)
subroutine deallocate_upwinding_local (u_local)
subroutine ns_rhs_weno (numDim, bufferSizes, numPointsBuffer, numScalars, numEquations, dir, sconn, dfluxbuffer, inviscidFluxBuffer, opInterval, gridMetric, jacobianDeterminant, gridCoordinates, gridType, rhoBuffer, rhoVBuffer, rhoEBuffer, pressureBuffer, temperatureBuffer, sosBuffer, scalarBuffer, WENO_alpha, wenoOptions, eosGasInfo, eosNonDimen, eosGasParams)
subroutine apply_weno_js_consistent (dir, p_map, smap, inviscidFluxBuffer, f_face_1d, index_weno, numEquations, numPointsBuffer, haveAxis, s)
subroutine conserved_variables_single_point (u, rhoBuffer, rhoVBuffer, rhoEBuffer, scalarBuffer, map, smap, numDim, nauxVars, numEquations, numPointsBuffer, haveAxis)
subroutine frozen_incviscid_flux (f_stencil, width, rhoBuffer, rhoVBuffer, rhoEBuffer, scalarBuffer, pressureBuffer, map, p_map, smap, numDim, nauxVars, numEquations, numPointsBuffer, MT1_freeze, haveAxis)
subroutine characteristic_velocity (ws_stencil, width, iLeft, iRight, rhoBuffer, rhoVBuffer, rhoEBuffer, scalarBuffer, pressureBuffer, temperatureBuffer, sosBuffer, map, p_map, smap, dir, numDim, nauxVars, numEquations, numPointsBuffer, gridMetric, jacobianDeterminant, eosInfo, eosNonDimen, eosGasParams, haveAxis, c_local)
subroutine computecharacteristicvelocities (numDim, numPointsBuffer, bufferSizes, opInterval, numEquations, nAuxVars, haveAxis, dir, velocityBuffer, sosBuffer, gridMetric, jacobianDeterminant, charVel)
subroutine characteristic_velocity_old (ws_stencil, width, iLeft, iRight, rhoBuffer, rhoVBuffer, rhoEBuffer, scalarBuffer, pressureBuffer, temperatureBuffer, sosBuffer, map, p_map, smap, dir, numDim, nauxVars, numEquations, numPointsBuffer, gridMetric, jacobianDeterminant, eosInfo, eosNonDimen, eosGasParams, haveAxis)
subroutine apply_weno_js_dissipation (dir, p_map, smap, numDim, numEquations, f_face_1d, index_weno, WENO_alpha, nAuxVars, WENO_STRONGSHOCKS, numPointsBuffer, rhoBuffer, rhoVBuffer, rhoEBuffer, scalarBuffer, pressureBuffer, temperatureBuffer, sosBuffer, gridMetric, jacobianDeterminant, eosInfo, eosNonDimen, eosGasParams, gridType, haveAxis, d_local, c_local, u_local)
subroutine apply_weno_js_dissipation_old (dir, p_map, smap, numDim, numEquations, f_face_1d, index_weno, WENO_alpha, nAuxVars, WENO_STRONGSHOCKS, numPointsBuffer, rhoBuffer, rhoVBuffer, rhoEBuffer, scalarBuffer, pressureBuffer, temperatureBuffer, sosBuffer, gridMetric, jacobianDeterminant, eosInfo, eosNonDimen, eosGasParams, gridType, haveAxis)
subroutine dissipation_part_by_upwinding_flux (f_stencil_char_sign, dir, numDim, numEquations, width, sign_flag, MT1_freeze, f_face_1d_char, u_local)
subroutine ns_rhs_muscl (numDim, bufferSizes, numPointsBuffer, normDir, sconn, opInterval, bufferInterval, gridType, gridMetric, jacobianDeterminant, bcParams, gasParams, numScalars, rhoBuffer, rhoVBuffer, rhoEBuffer, scalarBuffer, pressureBuffer, temperatureBuffer, sosBuffer, rhoRHSBuffer, rhoVRHSBuffer, rhoERHSBuffer, scalarRHSBuffer, WENO_alpha, wenoOptions, eosInfo, eosNonDimen, eosGasParams)
subroutine muscl_reconstruction (f_input, numEquations, NpencilW, i1, i2, i3, side, f_output)
subroutine inviscidflux (rhoBuffer, rhoVBuffer, rhoEBuffer, pressureBuffer, scalarBuffer, p_map, normdir, numDim, numScalars, numEquations, numPointsBuffer, gridMetric, Npencil, f_stencil)
subroutine inviscidflux_freeze (rhoBuffer, rhoVBuffer, rhoEBuffer, pressureBuffer, scalarBuffer, p_map, normdir, numDim, numScalars, numEquations, numPointsBuffer, MT1, Npencil, width, f_stencil)
subroutine ns_bc_weno (numDim, bufferSizes, numPointsBuffer, normDirIn, opInterval, bufferInterval, gridType, gridMetric, gridJacobian, MT2, bcType, bcParams, gasVars, numScalars, rhoBuffer, rhoVBuffer, rhoEBuffer, scalarBuffer, pressureBuffer, temperatureBuffer, sosBuffer, rhoRHSBuffer, rhoVRHSBuffer, rhoERHSBuffer, scalarRHSBuffer, eosInfo, eosNonDimen, eosGasParams)
subroutine ns_bc_fixvalue (numDim, bufferSizes, numPointsBuffer, normDirIn, numPatchPointsOp, patchPointsOp, gridType, gridMetric, gridJacobian, bcType, bcParams, gasVars, numScalars, pressureBuffer, temperatureBuffer, sosBuffer, eosInfo, eosNonDimen, eosGasParams, rhoTarget, rhoVTarget, rhoETarget, scalarTarget, rhoBuffer, rhoVBuffer, rhoEBuffer, scalarBuffer)
subroutine cross_product (v1, v2, y)
subroutine ns_rhs_axisymmetric (numDim, bufferSizes, numPointsBuffer, numScalars, opInterval, gridCoordinates, rhoBuffer, rhoVBuffer, rhoEBuffer, pressureBuffer, scalarBuffer, rhoRHSBuffer, rhoVRHSBuffer, rhoERHSBuffer, scalarRHSBuffer)
subroutine ns_rhs_axisymmetric_axis (numDim, bufferInterval, numPointsBuffer, numScalars, normDir, opInterval, gridMetric, jacobianDeterminant, gridType, gridCoordinates, rhoBuffer, rhoVBuffer, rhoEBuffer, pressureBuffer, scalarBuffer, rhoRHSBuffer, rhoVRHSBuffer, rhoERHSBuffer, scalarRHSBuffer)
Variables
integer(kind=4), parameter nscbc_noslip_isothermal = 6
integer(kind=4), parameter nscbc_slip_adiabatic = 7
integer(kind=4), parameter nscbc_inflow_supersonic = 8
integer(kind=4), parameter nscbc_inflow_subsonic = 9
integer(kind=4), parameter nscbc_inflow_veltemp = 10
integer(kind=4), parameter nscbc_outflow_nonreflection = 11
integer(kind=4), parameter nscbc_axisymmetry = 12
integer(kind=4), parameter weno_central = 1
integer(kind=4), parameter weno_leftboundary1 = 4
integer(kind=4), parameter weno_leftboundary2 = 8
integer(kind=4), parameter weno_rightboundary1 = 10
integer(kind=4), parameter weno_rightboundary2 = 14
integer(kind=4), parameter weno_axisboundary1 = 20
integer(kind=4), parameter weno_axisboundary2 = 26
integer, parameter ns = 3
integer(kind=4), parameter width = 6
Function/Subroutine Documentation
subroutine navierstokesrhsweno::allocate_local_types (type(dissipation_local) d_local, type(characteristic_local) c_local, type(upwinding_local) u_local, integer, intent(in) numEquations, integer, intent(in) numDim, integer, intent(in) nAuxVars)
Definition at line 78 of file NavierStokesRHSWENO.f90.
References allocate_upwinding_local(), and width.
Referenced by ns_rhs_weno().
subroutine navierstokesrhsweno::allocate_upwinding_local (type(upwinding_local) u_local, integer, intent(in) numEquations)
Definition at line 119 of file NavierStokesRHSWENO.f90.
References ns, and width.
Referenced by allocate_local_types(), and apply_weno_js_dissipation_old().
subroutine navierstokesrhsweno::apply_weno_js_consistent (integer(kind=4) dir, integer(kind=8), dimension(:) p_map, real(kind=8), dimension(:,:) smap, real(kind=8), dimension(numequations*numpointsbuffer) inviscidFluxBuffer, real(kind=8), dimension(:,:) f_face_1d, integer(kind=8), dimension(2) index_weno, integer(kind=4) numEquations, integer(kind=8) numPointsBuffer, integer(kind=4) haveAxis, integer, dimension(numequations) s)
Definition at line 453 of file NavierStokesRHSWENO.f90.
Referenced by ns_rhs_weno().
subroutine navierstokesrhsweno::apply_weno_js_dissipation (integer(kind=4), intent(in) dir, integer(kind=8), dimension(:), intent(in) p_map, real(kind=8), dimension(:,:), intent(in) smap, integer(kind=4), intent(in) numDim, integer(kind=4), intent(in) numEquations, real(kind=8), dimension(:,:), intent(out) f_face_1d, integer(kind=8), dimension(2), intent(in) index_weno, real(kind=8), intent(in) WENO_alpha, integer(kind=4), intent(in) nAuxVars, integer(kind=4), intent(in) WENO_STRONGSHOCKS, integer(kind=8), intent(in) numPointsBuffer, real(kind=8), dimension(numpointsbuffer), intent(in) rhoBuffer, real(kind=8), dimension(numdim*numpointsbuffer), intent(in), target rhoVBuffer, real(kind=8), dimension(numpointsbuffer), intent(in) rhoEBuffer, real(kind=8), dimension(nauxvars*numpointsbuffer), intent(in), target scalarBuffer, real(kind=8), dimension(numpointsbuffer), intent(in) pressureBuffer, real(kind=8), dimension(numpointsbuffer), intent(in) temperatureBuffer, real(kind=8), dimension(numpointsbuffer), intent(in) sosBuffer, real(kind=8), dimension(numdim*numdim*numpointsbuffer), intent(in) gridMetric, real(kind=8), dimension(numpointsbuffer), intent(in) jacobianDeterminant, integer(kind=8), dimension(numgasinfos), intent(in) eosInfo, real(kind=8), dimension(numnondimens), intent(in) eosNonDimen, real(kind=8), dimension(numgasparams*(nauxvars+1)), intent(in) eosGasParams, integer(kind=4), intent(in) gridType, integer(kind=4), intent(in) haveAxis, type(dissipation_local) d_local, type(characteristic_local) c_local, type(upwinding_local) u_local)
Definition at line 861 of file NavierStokesRHSWENO.f90.
References characteristic_velocity(), conserved_variables_single_point(), dissipation_part_by_upwinding_flux(), frozen_incviscid_flux(), and width.
Referenced by ns_rhs_weno().
subroutine navierstokesrhsweno::apply_weno_js_dissipation_old (integer(kind=4), intent(in) dir, integer(kind=8), dimension(:) p_map, real(kind=8), dimension(:,:), intent(in) smap, integer(kind=4), intent(in) numDim, integer(kind=4), intent(in) numEquations, real(kind=8), dimension(:,:), intent(out) f_face_1d, integer(kind=8), dimension(2) index_weno, real(kind=8) WENO_alpha, integer(kind=4), intent(in) nAuxVars, integer(kind=4) WENO_STRONGSHOCKS, integer(kind=8) numPointsBuffer, real(kind=8), dimension(numpointsbuffer), intent(in) rhoBuffer, real(kind=8), dimension(numdim*numpointsbuffer), intent(in), target rhoVBuffer, real(kind=8), dimension(numpointsbuffer), intent(in) rhoEBuffer, real(kind=8), dimension(nauxvars*numpointsbuffer), intent(in), target scalarBuffer, real(kind=8), dimension(numpointsbuffer), intent(in) pressureBuffer, real(kind=8), dimension(numpointsbuffer), intent(in) temperatureBuffer, real(kind=8), dimension(numpointsbuffer), intent(in) sosBuffer, real(kind=8), dimension(numdim*numdim*numpointsbuffer) gridMetric, real(kind=8), dimension(numpointsbuffer) jacobianDeterminant, integer(kind=8), dimension(numgasinfos) eosInfo, real(kind=8), dimension(numnondimens), intent(in) eosNonDimen, real(kind=8), dimension(numgasparams*(nauxvars+1)), intent(in) eosGasParams, integer(kind=4), intent(in) gridType, integer(kind=4) haveAxis)
Definition at line 1046 of file NavierStokesRHSWENO.f90.
References allocate_upwinding_local(), characteristic_velocity_old(), conserved_variables_single_point(), deallocate_upwinding_local(), dissipation_part_by_upwinding_flux(), frozen_incviscid_flux(), and width.
Referenced by ns_rhs_muscl().
subroutine navierstokesrhsweno::characteristic_velocity (real(kind=8), dimension(width+1,numequations), intent(out) ws_stencil, integer(kind=4) width, integer(kind=4) iLeft, integer(kind=4) iRight, real(kind=8), dimension(numpointsbuffer), intent(in) rhoBuffer, real(kind=8), dimension(numdim*numpointsbuffer), intent(in), target rhoVBuffer, real(kind=8), dimension(numpointsbuffer), intent(in) rhoEBuffer, real(kind=8), dimension(nauxvars*numpointsbuffer), intent(in), target scalarBuffer, real(kind=8), dimension(numpointsbuffer), intent(in) pressureBuffer, real(kind=8), dimension(numpointsbuffer), intent(in) temperatureBuffer, real(kind=8), dimension(numpointsbuffer), intent(in) sosBuffer, integer(kind=4) map, integer(kind=8), dimension(:) p_map, real(kind=8), dimension(:,:) smap, integer(kind=4) dir, integer(kind=4) numDim, integer(kind=4) nauxVars, integer(kind=4) numEquations, integer(kind=8) numPointsBuffer, real(kind=8), dimension(numdim*numdim*numpointsbuffer) gridMetric, real(kind=8), dimension(numpointsbuffer) jacobianDeterminant, integer(kind=8), dimension(numgasinfos) eosInfo, real(kind=8), dimension(numnondimens), intent(in) eosNonDimen, real(kind=8), dimension(numgasparams*(nauxvars+1)), intent(in) eosGasParams, integer(kind=4) haveAxis, type(characteristic_local) c_local)
Definition at line 605 of file NavierStokesRHSWENO.f90.
References conserved_variables_single_point().
Referenced by apply_weno_js_dissipation().
subroutine navierstokesrhsweno::characteristic_velocity_old (real(kind=8), dimension(width+1,numequations), intent(out) ws_stencil, integer(kind=4) width, integer(kind=4) iLeft, integer(kind=4) iRight, real(kind=8), dimension(numpointsbuffer), intent(in) rhoBuffer, real(kind=8), dimension(numdim*numpointsbuffer), intent(in), target rhoVBuffer, real(kind=8), dimension(numpointsbuffer), intent(in) rhoEBuffer, real(kind=8), dimension(nauxvars*numpointsbuffer), intent(in), target scalarBuffer, real(kind=8), dimension(numpointsbuffer), intent(in) pressureBuffer, real(kind=8), dimension(numpointsbuffer), intent(in) temperatureBuffer, real(kind=8), dimension(numpointsbuffer), intent(in) sosBuffer, integer(kind=4) map, integer(kind=8), dimension(:) p_map, real(kind=8), dimension(:,:) smap, integer(kind=4) dir, integer(kind=4) numDim, integer(kind=4) nauxVars, integer(kind=4) numEquations, integer(kind=8) numPointsBuffer, real(kind=8), dimension(numdim*numdim*numpointsbuffer) gridMetric, real(kind=8), dimension(numpointsbuffer) jacobianDeterminant, integer(kind=8), dimension(numgasinfos) eosInfo, real(kind=8), dimension(numnondimens), intent(in) eosNonDimen, real(kind=8), dimension(numgasparams*(nauxvars+1)), intent(in) eosGasParams, integer(kind=4) haveAxis)
Definition at line 770 of file NavierStokesRHSWENO.f90.
References conserved_variables_single_point().
Referenced by apply_weno_js_dissipation_old(), and ns_rhs_muscl().
subroutine navierstokesrhsweno::computecharacteristicvelocities (integer(kind=4), intent(in) numDim, integer(kind=8), intent(in) numPointsBuffer, integer(kind=8), dimension(numdim), intent(in) bufferSizes, integer(kind=8), dimension(2*numdim), intent(in) opInterval, integer(kind=4), intent(in) numEquations, integer(kind=4), intent(in) nAuxVars, integer(kind=4), intent(in) haveAxis, integer(kind=4), intent(in) dir, real(kind=8), dimension(numdim*numpointsbuffer), intent(in) velocityBuffer, real(kind=8), dimension(numpointsbuffer), intent(in) sosBuffer, real(kind=8), dimension(numdim*numdim*numpointsbuffer), intent(in) gridMetric, real(kind=8), dimension(numpointsbuffer), intent(in) jacobianDeterminant, real(kind=8), dimension(3*numpointsbuffer), intent(out) charVel)
Definition at line 701 of file NavierStokesRHSWENO.f90.
subroutine navierstokesrhsweno::conserved_variables_single_point (real(kind=8), dimension(numequations) u, real(kind=8), dimension(numpointsbuffer), intent(in) rhoBuffer, real(kind=8), dimension(numdim*numpointsbuffer), intent(in), target rhoVBuffer, real(kind=8), dimension(numpointsbuffer), intent(in) rhoEBuffer, real(kind=8), dimension(nauxvars*numpointsbuffer), intent(in), target scalarBuffer, integer(kind=8) map, real(kind=8), dimension(:) smap, integer(kind=4) numDim, integer(kind=4) nauxVars, integer(kind=4) numEquations, integer(kind=8) numPointsBuffer, integer(kind=4) haveAxis)
Definition at line 503 of file NavierStokesRHSWENO.f90.
Referenced by apply_weno_js_dissipation(), apply_weno_js_dissipation_old(), characteristic_velocity(), characteristic_velocity_old(), ns_bc_fixvalue(), ns_bc_weno(), and ns_rhs_muscl().
subroutine navierstokesrhsweno::cross_product (real(kind=8), dimension(3) v1, real(kind=8), dimension(3) v2, real(kind=8), dimension(3) y)
Definition at line 2813 of file NavierStokesRHSWENO.f90.
Referenced by ns_bc_fixvalue().
subroutine navierstokesrhsweno::deallocate_local_types (type(dissipation_local) d_local, type(characteristic_local) c_local, type(upwinding_local) u_local)
Definition at line 131 of file NavierStokesRHSWENO.f90.
References deallocate_upwinding_local().
Referenced by ns_rhs_weno().
subroutine navierstokesrhsweno::deallocate_upwinding_local (type(upwinding_local) u_local)
Definition at line 170 of file NavierStokesRHSWENO.f90.
Referenced by apply_weno_js_dissipation_old(), and deallocate_local_types().
subroutine navierstokesrhsweno::dissipation_part_by_upwinding_flux (real(kind=8), dimension(width,numequations) f_stencil_char_sign, integer(kind=4) dir, integer(kind=4) numDim, integer(kind=4) numEquations, integer(kind=4) width, integer(kind=4) sign_flag, real(kind=8), dimension(numdim) MT1_freeze, real(kind=8), dimension(numequations) f_face_1d_char, type(upwinding_local) u_local)
Definition at line 1220 of file NavierStokesRHSWENO.f90.
Referenced by apply_weno_js_dissipation(), and apply_weno_js_dissipation_old().
subroutine navierstokesrhsweno::frozen_incviscid_flux (real(kind=8), dimension(width,numequations) f_stencil, integer(kind=4) width, real(kind=8), dimension(numpointsbuffer), intent(in) rhoBuffer, real(kind=8), dimension(numdim*numpointsbuffer), intent(in), target rhoVBuffer, real(kind=8), dimension(numpointsbuffer), intent(in) rhoEBuffer, real(kind=8), dimension(nauxvars*numpointsbuffer), intent(in), target scalarBuffer, real(kind=8), dimension(numpointsbuffer), intent(in) pressureBuffer, integer(kind=4) map, integer(kind=8), dimension(:) p_map, real(kind=8), dimension(:,:) smap, integer(kind=4) numDim, integer(kind=4) nauxVars, integer(kind=4) numEquations, integer(kind=8) numPointsBuffer, real(kind=8), dimension(numdim), intent(in) MT1_freeze, integer(kind=4) haveAxis)
Definition at line 538 of file NavierStokesRHSWENO.f90.
Referenced by apply_weno_js_dissipation(), and apply_weno_js_dissipation_old().
subroutine navierstokesrhsweno::inviscidflux (real(kind=8), dimension(numpointsbuffer), intent(in) rhoBuffer, real(kind=8), dimension(numdim*numpointsbuffer), intent(in), target rhoVBuffer, real(kind=8), dimension(numpointsbuffer), intent(in) rhoEBuffer, real(kind=8), dimension(numpointsbuffer), intent(in) pressureBuffer, real(kind=8), dimension(numscalars*numpointsbuffer), intent(in), target scalarBuffer, integer(kind=8), dimension(:), intent(in) p_map, integer(kind=4) normdir, integer(kind=4) numDim, integer(kind=4) numScalars, integer(kind=4) numEquations, integer(kind=8) numPointsBuffer, real(kind=8), dimension(numdim*numdim*numpointsbuffer), intent(in) gridMetric, integer(kind=4) Npencil, real(kind=8), dimension(npencil,numequations), intent(out) f_stencil)
Definition at line 1817 of file NavierStokesRHSWENO.f90.
Referenced by ns_rhs_muscl().
subroutine navierstokesrhsweno::inviscidflux_freeze (real(kind=8), dimension(numpointsbuffer), intent(in) rhoBuffer, real(kind=8), dimension(numdim*numpointsbuffer), intent(in), target rhoVBuffer, real(kind=8), dimension(numpointsbuffer), intent(in) rhoEBuffer, real(kind=8), dimension(numpointsbuffer), intent(in) pressureBuffer, real(kind=8), dimension(numscalars*numpointsbuffer), intent(in), target scalarBuffer, integer(kind=8), dimension(:), intent(in) p_map, integer(kind=4) normdir, integer(kind=4) numDim, integer(kind=4) numScalars, integer(kind=4) numEquations, integer(kind=8) numPointsBuffer, real(kind=8), dimension(numdim), intent(in) MT1, integer(kind=4) Npencil, integer(kind=4) width, real(kind=8), dimension(npencil,numequations), intent(out) f_stencil)
Definition at line 1865 of file NavierStokesRHSWENO.f90.
Referenced by ns_rhs_muscl().
subroutine navierstokesrhsweno::muscl_reconstruction (real(kind=8), dimension(npencilw,numequations) f_input, integer(kind=4) numEquations, integer(kind=4) NpencilW, integer(kind=4) i1, integer(kind=4) i2, integer(kind=4) i3, real(kind=8) side, real(kind=8), dimension(numequations) f_output)
Definition at line 1794 of file NavierStokesRHSWENO.f90.
Referenced by ns_rhs_muscl().
subroutine navierstokesrhsweno::ns_bc_fixvalue (integer(kind=4) numDim, integer(kind=8), dimension(numdim) bufferSizes, integer(kind=8) numPointsBuffer, integer(kind=4) normDirIn, integer(kind=8) numPatchPointsOp, integer(kind=8), dimension(numpatchpointsop) patchPointsOp, integer(kind=4) gridType, real(kind=8), dimension(numdim*numdim*numpointsbuffer), intent(in) gridMetric, real(kind=8), dimension(numpointsbuffer), intent(in) gridJacobian, integer(kind=4) bcType, real(kind=8), dimension(5), intent(in) bcParams, real(kind=8), dimension(6), intent(in) gasVars, integer(kind=4) numScalars, real(kind=8), dimension(numpointsbuffer), intent(in) pressureBuffer, real(kind=8), dimension(numpointsbuffer), intent(in) temperatureBuffer, real(kind=8), dimension(numpointsbuffer), intent(in) sosBuffer, integer(kind=8), dimension(numgasinfos) eosInfo, real(kind=8), dimension(numnondimens), intent(in) eosNonDimen, real(kind=8), dimension(numgasparams*(numscalars+1)), intent(in) eosGasParams, real(kind=8), dimension(numpointsbuffer), intent(in) rhoTarget, real(kind=8), dimension(numdim*numpointsbuffer), intent(in), target rhoVTarget, real(kind=8), dimension(numpointsbuffer), intent(in) rhoETarget, real(kind=8), dimension(numscalars*numpointsbuffer), intent(in), target scalarTarget, real(kind=8), dimension(numpointsbuffer), intent(inout) rhoBuffer, real(kind=8), dimension(numdim*numpointsbuffer), intent(inout), target rhoVBuffer, real(kind=8), dimension(numpointsbuffer), intent(inout) rhoEBuffer, real(kind=8), dimension(numscalars*numpointsbuffer), intent(inout), target scalarBuffer)
BC FixValue for different metric types [mtc]
Definition at line 2500 of file NavierStokesRHSWENO.f90.
References conserved_variables_single_point(), cross_product(), nscbc_axisymmetry, nscbc_inflow_subsonic, nscbc_inflow_supersonic, nscbc_inflow_veltemp, nscbc_noslip_isothermal, and nscbc_slip_adiabatic.
subroutine navierstokesrhsweno::ns_bc_weno (integer(kind=4) numDim, integer(kind=8), dimension(numdim) bufferSizes, integer(kind=8) numPointsBuffer, integer(kind=4) normDirIn, integer(kind=8), dimension(2*numdim), intent(in) opInterval, integer(kind=8), dimension(2*numdim), intent(in) bufferInterval, integer(kind=4) gridType, real(kind=8), dimension(numdim*numdim*numpointsbuffer), intent(inout) gridMetric, real(kind=8), dimension(numpointsbuffer), intent(inout) gridJacobian, real(kind=8), dimension(numdim*numdim*numpointsbuffer), intent(in) MT2, integer(kind=4) bcType, real(kind=8), dimension(5), intent(in) bcParams, real(kind=8), dimension(6), intent(in) gasVars, integer(kind=4) numScalars, real(kind=8), dimension(numpointsbuffer), intent(in) rhoBuffer, real(kind=8), dimension(numdim*numpointsbuffer), intent(in), target rhoVBuffer, real(kind=8), dimension(numpointsbuffer), intent(in) rhoEBuffer, real(kind=8), dimension(numscalars*numpointsbuffer), intent(in), target scalarBuffer, real(kind=8), dimension(numpointsbuffer), intent(in) pressureBuffer, real(kind=8), dimension(numpointsbuffer), intent(in) temperatureBuffer, real(kind=8), dimension(numpointsbuffer), intent(in) sosBuffer, real(kind=8), dimension(numpointsbuffer), intent(inout) rhoRHSBuffer, real(kind=8), dimension(numdim*numpointsbuffer), intent(inout), target rhoVRHSBuffer, real(kind=8), dimension(numpointsbuffer), intent(inout) rhoERHSBuffer, real(kind=8), dimension(numscalars*numpointsbuffer), intent(inout), target scalarRHSBuffer, integer(kind=8), dimension(numgasinfos) eosInfo, real(kind=8), dimension(numnondimens), intent(in) eosNonDimen, real(kind=8), dimension(numgasparams*(numscalars+1)), intent(in) eosGasParams)
Definition at line 1917 of file NavierStokesRHSWENO.f90.
References conserved_variables_single_point(), nscbc_axisymmetry, nscbc_inflow_veltemp, nscbc_noslip_isothermal, nscbc_outflow_nonreflection, and nscbc_slip_adiabatic.
subroutine navierstokesrhsweno::ns_rhs_axisymmetric (integer(kind=4) numDim, integer(kind=8), dimension(numdim) bufferSizes, integer(kind=8) numPointsBuffer, integer(kind=4) numScalars, integer(kind=8), dimension(2*numdim), intent(in) opInterval, real(kind=8), dimension(numdim*numpointsbuffer), intent(in), target gridCoordinates, real(kind=8), dimension(numpointsbuffer), intent(in) rhoBuffer, real(kind=8), dimension(numdim*numpointsbuffer), intent(in), target rhoVBuffer, real(kind=8), dimension(numpointsbuffer), intent(in) rhoEBuffer, real(kind=8), dimension(numpointsbuffer), intent(in) pressureBuffer, real(kind=8), dimension(numscalars*numpointsbuffer), intent(in), target scalarBuffer, real(kind=8), dimension(numpointsbuffer), intent(inout) rhoRHSBuffer, real(kind=8), dimension(numdim*numpointsbuffer), intent(inout), target rhoVRHSBuffer, real(kind=8), dimension(numpointsbuffer), intent(inout) rhoERHSBuffer, real(kind=8), dimension(numscalars*numpointsbuffer), intent(inout), target scalarRHSBuffer)
Definition at line 2832 of file NavierStokesRHSWENO.f90.
subroutine navierstokesrhsweno::ns_rhs_axisymmetric_axis (integer(kind=4) numDim, integer(kind=8), dimension(2*numdim), intent(in) bufferInterval, integer(kind=8) numPointsBuffer, integer(kind=4) numScalars, integer(kind=4) normDir, integer(kind=8), dimension(2*numdim), intent(in) opInterval, real(kind=8), dimension(numdim*numdim*numpointsbuffer), intent(in) gridMetric, real(kind=8), dimension(2*numpointsbuffer), intent(in) jacobianDeterminant, integer(kind=4) gridType, real(kind=8), dimension(numdim*numpointsbuffer), intent(in), target gridCoordinates, real(kind=8), dimension(numpointsbuffer), intent(in) rhoBuffer, real(kind=8), dimension(numdim*numpointsbuffer), intent(in), target rhoVBuffer, real(kind=8), dimension(numpointsbuffer), intent(in) rhoEBuffer, real(kind=8), dimension(numpointsbuffer), intent(in) pressureBuffer, real(kind=8), dimension(numscalars*numpointsbuffer), intent(in), target scalarBuffer, real(kind=8), dimension(numpointsbuffer), intent(inout) rhoRHSBuffer, real(kind=8), dimension(numdim*numpointsbuffer), intent(inout), target rhoVRHSBuffer, real(kind=8), dimension(numpointsbuffer), intent(inout) rhoERHSBuffer, real(kind=8), dimension(numscalars*numpointsbuffer), intent(inout), target scalarRHSBuffer)
Definition at line 2888 of file NavierStokesRHSWENO.f90.
subroutine navierstokesrhsweno::ns_rhs_muscl (integer(kind=4) numDim, integer(kind=8), dimension(numdim) bufferSizes, integer(kind=8) numPointsBuffer, integer(kind=4) normDir, integer(kind=4), dimension(numpointsbuffer) sconn, integer(kind=8), dimension(2*numdim), intent(in) opInterval, integer(kind=8), dimension(2*numdim), intent(in) bufferInterval, integer(kind=4) gridType, real(kind=8), dimension(numdim*numdim*numpointsbuffer), intent(in) gridMetric, real(kind=8), dimension(numpointsbuffer), intent(in) jacobianDeterminant, real(kind=8), dimension(5), intent(in) bcParams, real(kind=8), dimension(5), intent(in) gasParams, integer(kind=4) numScalars, real(kind=8), dimension(numpointsbuffer), intent(in) rhoBuffer, real(kind=8), dimension(numdim*numpointsbuffer), intent(in), target rhoVBuffer, real(kind=8), dimension(numpointsbuffer), intent(in) rhoEBuffer, real(kind=8), dimension(numscalars*numpointsbuffer), intent(in), target scalarBuffer, real(kind=8), dimension(numpointsbuffer), intent(in) pressureBuffer, real(kind=8), dimension(numpointsbuffer), intent(in) temperatureBuffer, real(kind=8), dimension(numpointsbuffer), intent(in) sosBuffer, real(kind=8), dimension(numpointsbuffer), intent(inout) rhoRHSBuffer, real(kind=8), dimension(numdim*numpointsbuffer), intent(inout), target rhoVRHSBuffer, real(kind=8), dimension(numpointsbuffer), intent(inout) rhoERHSBuffer, real(kind=8), dimension(numscalars*numpointsbuffer), intent(inout), target scalarRHSBuffer, real(kind=8) WENO_alpha, integer(kind=4), dimension(2) wenoOptions, integer(kind=8), dimension(numgasinfos) eosInfo, real(kind=8), dimension(numnondimens), intent(in) eosNonDimen, real(kind=8), dimension(numgasparams*(numscalars+1)), intent(in) eosGasParams)
Definition at line 1306 of file NavierStokesRHSWENO.f90.
References apply_weno_js_dissipation_old(), characteristic_velocity_old(), conserved_variables_single_point(), inviscidflux(), inviscidflux_freeze(), and muscl_reconstruction().
subroutine navierstokesrhsweno::ns_rhs_weno (integer(kind=4) numDim, integer(kind=8), dimension(numdim) bufferSizes, integer(kind=8) numPointsBuffer, integer(kind=4) numScalars, integer(kind=4) numEquations, integer(kind=4) dir, integer(kind=4), dimension(numpointsbuffer) sconn, real(kind=8), dimension(numequations*numpointsbuffer) dfluxbuffer, real(kind=8), dimension(numequations*numpointsbuffer), intent(in) inviscidFluxBuffer, integer(kind=8), dimension(2*numdim), intent(in) opInterval, real(kind=8), dimension(numdim*numdim*numpointsbuffer), intent(in) gridMetric, real(kind=8), dimension(2*numpointsbuffer), intent(in) jacobianDeterminant, real(kind=8), dimension(numdim*numpointsbuffer), intent(in) gridCoordinates, integer(kind=4) gridType, real(kind=8), dimension(numpointsbuffer), intent(in) rhoBuffer, real(kind=8), dimension(numdim*numpointsbuffer), intent(in), target rhoVBuffer, real(kind=8), dimension(numpointsbuffer), intent(in) rhoEBuffer, real(kind=8), dimension(numpointsbuffer), intent(in) pressureBuffer, real(kind=8), dimension(numpointsbuffer), intent(in) temperatureBuffer, real(kind=8), dimension(numpointsbuffer), intent(in) sosBuffer, real(kind=8), dimension(numscalars*numpointsbuffer), intent(in), target scalarBuffer, real(kind=8) WENO_alpha, integer(kind=4), dimension(2) wenoOptions, integer(kind=8), dimension(numgasinfos) eosGasInfo, real(kind=8), dimension(numnondimens), intent(in) eosNonDimen, real(kind=8), dimension(numgasparams*(numscalars+1)), intent(in) eosGasParams)
Todo
Check with Pavel, sconn(1) will actually be in the halo [mtc]
Definition at line 195 of file NavierStokesRHSWENO.f90.
References allocate_local_types(), apply_weno_js_consistent(), apply_weno_js_dissipation(), deallocate_local_types(), weno_axisboundary1, weno_axisboundary2, weno_central, weno_leftboundary1, weno_leftboundary2, weno_rightboundary1, and weno_rightboundary2.
Variable Documentation
integer, parameter ns = 3
Definition at line 28 of file NavierStokesRHSWENO.f90.
Referenced by allocate_upwinding_local().
integer(kind=4), parameter nscbc_axisymmetry = 12
Definition at line 18 of file NavierStokesRHSWENO.f90.
Referenced by ns_bc_fixvalue(), and ns_bc_weno().
integer(kind=4), parameter nscbc_inflow_subsonic = 9
Definition at line 15 of file NavierStokesRHSWENO.f90.
Referenced by ns_bc_fixvalue().
integer(kind=4), parameter nscbc_inflow_supersonic = 8
Definition at line 14 of file NavierStokesRHSWENO.f90.
Referenced by ns_bc_fixvalue().
integer(kind=4), parameter nscbc_inflow_veltemp = 10
Definition at line 16 of file NavierStokesRHSWENO.f90.
Referenced by ns_bc_fixvalue(), and ns_bc_weno().
integer(kind=4), parameter nscbc_noslip_isothermal = 6
Definition at line 12 of file NavierStokesRHSWENO.f90.
Referenced by ns_bc_fixvalue(), and ns_bc_weno().
integer(kind=4), parameter nscbc_outflow_nonreflection = 11
Definition at line 17 of file NavierStokesRHSWENO.f90.
Referenced by ns_bc_weno().
integer(kind=4), parameter nscbc_slip_adiabatic = 7
Definition at line 13 of file NavierStokesRHSWENO.f90.
Referenced by ns_bc_fixvalue(), and ns_bc_weno().
integer(kind=4), parameter weno_axisboundary1 = 20
Definition at line 25 of file NavierStokesRHSWENO.f90.
Referenced by ns_rhs_weno().
integer(kind=4), parameter weno_axisboundary2 = 26
Definition at line 26 of file NavierStokesRHSWENO.f90.
Referenced by ns_rhs_weno().
integer(kind=4), parameter weno_central = 1
Definition at line 20 of file NavierStokesRHSWENO.f90.
Referenced by ns_rhs_weno().
integer(kind=4), parameter weno_leftboundary1 = 4
Definition at line 21 of file NavierStokesRHSWENO.f90.
Referenced by ns_rhs_weno().
integer(kind=4), parameter weno_leftboundary2 = 8
Definition at line 22 of file NavierStokesRHSWENO.f90.
Referenced by ns_rhs_weno().
integer(kind=4), parameter weno_rightboundary1 = 10
Definition at line 23 of file NavierStokesRHSWENO.f90.
Referenced by ns_rhs_weno().
integer(kind=4), parameter weno_rightboundary2 = 14
Definition at line 24 of file NavierStokesRHSWENO.f90.
Referenced by ns_rhs_weno().
integer(kind=4), parameter width = 6
Definition at line 29 of file NavierStokesRHSWENO.f90.
Referenced by allocate_local_types(), allocate_upwinding_local(), apply_weno_js_dissipation(), and apply_weno_js_dissipation_old().
Author
Generated automatically by Doxygen for JustKernels from the source code.