.TH "upwinding_local" 3 "Fri Apr 10 2020" "Version 1.0" "JustKernels" \" -*- nroff -*-
.ad l
.nh
.SH NAME
upwinding_local \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "real(kind=8), dimension(:,:), allocatable \fBf_stencil_char\fP"
.br
.ti -1c
.RI "real(kind=8), dimension(:), allocatable \fBc\fP"
.br
.ti -1c
.RI "real(kind=8), dimension(:,:), allocatable \fBis\fP"
.br
.ti -1c
.RI "real(kind=8), dimension(:,:), allocatable \fBalpha\fP"
.br
.ti -1c
.RI "real(kind=8), dimension(:,:), allocatable \fBw\fP"
.br
.ti -1c
.RI "real(kind=8), dimension(:,:), allocatable \fBtp\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 66 of file NavierStokesRHSWENO\&.f90\&.
.SH "Member Data Documentation"
.PP 
.SS "real(kind=8), dimension(:,:), allocatable alpha"

.PP
Definition at line 70 of file NavierStokesRHSWENO\&.f90\&.
.SS "real(kind=8), dimension(:), allocatable c"

.PP
Definition at line 68 of file NavierStokesRHSWENO\&.f90\&.
.SS "real(kind=8), dimension(:,:), allocatable f_stencil_char"

.PP
Definition at line 67 of file NavierStokesRHSWENO\&.f90\&.
.SS "real(kind=8), dimension(:,:), allocatable is"

.PP
Definition at line 69 of file NavierStokesRHSWENO\&.f90\&.
.SS "real(kind=8), dimension(:,:), allocatable tp"

.PP
Definition at line 72 of file NavierStokesRHSWENO\&.f90\&.
.SS "real(kind=8), dimension(:,:), allocatable w"

.PP
Definition at line 71 of file NavierStokesRHSWENO\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for JustKernels from the source code\&.
