.TH "nsutil" 3 "Fri Apr 10 2020" "Version 1.0" "JustKernels" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nsutil \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBgetpointstate\fP (\fBnumDim\fP, \fBnumScalar\fP, \fBnumPointsBuffer\fP, \fBrhoBuffer\fP, \fBrhoVBuffer\fP, \fBrhoEBuffer\fP, \fBscalarBuffer\fP, \fBpointID\fP, \fBpointState\fP)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine nsutil::getpointstate (integer(kind=4), intent(in) numDim, integer(kind=4), intent(in) numScalar, integer(kind=8), intent(in) numPointsBuffer, real(kind=8), dimension(numpointsbuffer), intent(in) rhoBuffer, real(kind=8), dimension(numdim*numpointsbuffer), intent(in) rhoVBuffer, real(kind=8), dimension(numpointsbuffer), intent(in) rhoEBuffer, real(kind=8), dimension(numscalar*numpointsbuffer), intent(in) scalarBuffer, integer(kind=8), intent(in) pointID, real(kind=8), dimension(numdim+2+numscalar), intent(out) pointState)"

.PP
Definition at line 9 of file NavierStokesUtil\&.f90\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for JustKernels from the source code\&.
