operators
NAME
operators -
SYNOPSIS
Functions/Subroutines
subroutine applyoperator (numDim, dimSizes, numComponents, numPoints, opDir, opInterval, numStencils, stencilSizes, stencilStarts, numValues, stencilWeights, stencilOffsets, stencilID, U, dU)
applyoperator applies an operator specified as a stencil set to the provided state data
subroutine applyoperatorv (numDim, dimSizes, numComponents, numPoints, opDir, opInterval, numStencils, stencilSizes, stencilStarts, numValues, stencilWeights, stencilOffsets, stencilID, U, dU)
applyoperator applies an operator specified as a stencil set to the provided state data
subroutine applyoperatorblobs (numDim, dimSizes, numComponents, numPointsBuffer, opDir, numStencils, stencilSizes, stencilStarts, numStencilValues, stencilWeights, stencilOffsets, numPointsStencil, numPointsApply, stencilPoints, U, dU)
applyoperatorblobs applies an operator by applying each stencil in turn to all the points to which it applies
subroutine applysinglestencil (numDim, dimSizes, numComponents, numPointsBuffer, opDir, numPointsApply, applyPoints, stencilSize, stencilWeights, stencilOffsets, U, dU)
applysinglestencil applies an operator by applying a given stencil to the specified points
Function/Subroutine Documentation
subroutine operators::applyoperator (integer(kind=4), intent(in) numDim, integer(kind=8), dimension(numdim), intent(in) dimSizes, integer(kind=4), intent(in) numComponents, integer(kind=8), intent(in) numPoints, integer(kind=4), intent(in) opDir, integer(kind=8), dimension(2*numdim), intent(in) opInterval, integer(kind=4), intent(in) numStencils, integer(kind=4), dimension(numstencils), intent(in) stencilSizes, integer(kind=4), dimension(numstencils), intent(in) stencilStarts, integer(kind=4), intent(in) numValues, real(kind=8), dimension(numvalues), intent(in) stencilWeights, integer(kind=4), dimension(numvalues), intent(in) stencilOffsets, integer(kind=4), dimension(numpoints), intent(in) stencilID, real(kind=8), dimension(numpoints*numcomponents), intent(in), target U, real(kind=8), dimension(numpoints*numcomponents), intent(out), target dU)
applyoperator applies an operator specified as a stencil set to the provided state data applyoperator is a brute-force method of applying a set of stencils to a given data buffer. The The stencilset and operand are given as flat, primitive arrays, with supporting data to indicate the size of the data structures. An additional stencil connectivity is given which indicates which stencil (i.e. which stencil from the stencil set) to apply to each point. This brute-force method simply loops through all points, and applies the stencil indicated by the resolved stencil connectivity to each point. applyoperator brute-force method cartoon
Parameters:
numDim indicates the number of dimensions for the input data (dimSizes,opInterval)
dimSizes indicates the number of points in each dimension [Nx Ny Nz]
numComponents indicates the number of components in the input/output data (U,dU)
numPoints indicates the total number of points Nx*Ny*Nz
opDir indicates in which direction the operator will be applied [X=1 | Y=2 | Z=3]
opInterval array of size (2*numDim) which indicates the index interval on which to operate [xStart,xEnd,yStart,yEnd...]
numStencils indicates the number of stencils in the input stencilset
stencilSizes array of size (numStencils) which indicates the number of weight values for each stencil
stencilStarts array of size (numStencils) which indicates the starting index into (stencilWeights and stencilOffsets) for each stencil
numValues total number of stencil weight values (numStencils[1]*numStencils[2]*...numStecils[numStencils]) (req'd for C/Fort interface)
stencilWeights array of size (numValues) which contains the weights for all the stencils in the stencilset
stencilOffsets array of size (numValues) which indicates the offsets from the considered point to the point where each weight is applied
stencilID array of size (numPoints) which indicates the stencil ID for each point
U the data on which to operate
dU where to stuff the result
Definition at line 37 of file Operators.f90.
Referenced by grid::computecurvilineargridmetrics().
subroutine operators::applyoperatorblobs (integer(kind=4), intent(in) numDim, integer(kind=8), dimension(numdim), intent(in) dimSizes, integer(kind=4), intent(in) numComponents, integer(kind=8), intent(in) numPointsBuffer, integer(kind=4), intent(in) opDir, integer(kind=4), intent(in) numStencils, integer(kind=4), dimension(numstencils), intent(in) stencilSizes, integer(kind=4), dimension(numstencils), intent(in) stencilStarts, integer(kind=4), intent(in) numStencilValues, real(kind=8), dimension(numstencilvalues), intent(in) stencilWeights, integer(kind=4), dimension(numstencilvalues), intent(in) stencilOffsets, integer(kind=8), dimension(numstencils), intent(in) numPointsStencil, integer(kind=8), intent(in) numPointsApply, integer(kind=8), dimension(numpointsapply), intent(in) stencilPoints, real(kind=8), dimension(numpointsbuffer), intent(in) U, real(kind=8), dimension(numpointsbuffer), intent(out) dU)
applyoperatorblobs applies an operator by applying each stencil in turn to all the points to which it applies applyoperatorblobs is a blobbed method of applying a set of stencils to a given data buffer. The stencilset and operand are given as flat, primitive arrays, with supporting data to indicate the size of the data structures. An additional dual stencil connectivity is given which indicates which points to apply to a given stencil. This blobbed method loops through all the stencils, and applies each stencil to the set of pionts indicated by the resolved dual stencil connectivity for each stencil. applyoperatorBLOBS - blobbed method cartoon
Parameters:
numDim indicates the number of dimensions for the input data (dimSizes,opInterval)
dimSizes indicates the number of points in each dimension [Nx Ny Nz]
numComponents indicates the number of components in the input/output data (U,dU)
numPointsBuffer indicates the total number of points Nx*Ny*Nz
opDir indicates in which direction the operator will be applied [X=1 | Y=2 | Z=3]
numStencils indicates the number of stencils in the input stencilset
stencilSizes array of size (numStencils) which indicates the number of weight values for each stencil
stencilStarts array of size (numStencils) which indicates the starting index into (stencilWeights and stencilOffsets) for each stencil
numStencilValues total number of stencil weight values (numStencils[1]*numStencils[2]*...numStecils[numStencils]) (req'd for C/Fort interface)
stencilWeights array of size (numValues) which contains the weights for all the stencils in the stencilset
stencilOffsets array of size (numValues) which indicates the offsets from the considered point to the point where each weight is applied
numPointsStencil array of size (numStencils) which indicates how many points to apply each stencil
numPointsApply total number of points in the stencilPoints array (needed for C/Fortran interface)
stencilPoints array of size (numPointsStencil(1)*numPointsStencil(2)*...numPointsStencil(numStencils)) indicating the points to which each stencil applies
U the data on which to operate
dU where to stuff the result
Definition at line 313 of file Operators.f90.
References applysinglestencil().
subroutine operators::applyoperatorv (integer(kind=4), intent(in) numDim, integer(kind=8), dimension(numdim), intent(in) dimSizes, integer(kind=4), intent(in) numComponents, integer(kind=8), intent(in) numPoints, integer(kind=4), intent(in) opDir, integer(kind=8), dimension(2*numdim), intent(in) opInterval, integer(kind=4), intent(in) numStencils, integer(kind=4), dimension(numstencils), intent(in) stencilSizes, integer(kind=4), dimension(numstencils), intent(in) stencilStarts, integer(kind=4), intent(in) numValues, real(kind=8), dimension(numvalues), intent(in) stencilWeights, integer(kind=4), dimension(numvalues), intent(in) stencilOffsets, integer(kind=4), dimension(numpoints), intent(in) stencilID, real(kind=8), dimension(numpoints*numcomponents), intent(in), target U, real(kind=8), dimension(numpoints*numcomponents), intent(out), target dU)
applyoperator applies an operator specified as a stencil set to the provided state data applyoperator is a brute-force method of applying a set of stencils to a given data buffer. The The stencilset and operand are given as flat, primitive arrays, with supporting data to indicate the size of the data structures. An additional stencil connectivity is given which indicates which stencil (i.e. which stencil from the stencil set) to apply to each point. This brute-force method simply loops through all points, and applies the stencil indicated by the resolved stencil connectivity to each point. applyoperator brute-force method cartoon
Parameters:
numDim indicates the number of dimensions for the input data (dimSizes,opInterval)
dimSizes indicates the number of points in each dimension [Nx Ny Nz]
numComponents indicates the number of components in the input/output data (U,dU)
numPoints indicates the total number of points Nx*Ny*Nz
opDir indicates in which direction the operator will be applied [X=1 | Y=2 | Z=3]
opInterval array of size (2*numDim) which indicates the index interval on which to operate [xStart,xEnd,yStart,yEnd...]
numStencils indicates the number of stencils in the input stencilset
stencilSizes array of size (numStencils) which indicates the number of weight values for each stencil
stencilStarts array of size (numStencils) which indicates the starting index into (stencilWeights and stencilOffsets) for each stencil
numValues total number of stencil weight values (numStencils[1]*numStencils[2]*...numStecils[numStencils]) (req'd for C/Fort interface)
stencilWeights array of size (numValues) which contains the weights for all the stencils in the stencilset
stencilOffsets array of size (numValues) which indicates the offsets from the considered point to the point where each weight is applied
stencilID array of size (numPoints) which indicates the stencil ID for each point
U the data on which to operate
dU where to stuff the result
Definition at line 175 of file Operators.f90.
subroutine operators::applysinglestencil (integer(kind=4), intent(in) numDim, integer(kind=8), dimension(numdim), intent(in) dimSizes, integer(kind=4), intent(in) numComponents, integer(kind=8), intent(in) numPointsBuffer, integer(kind=4), intent(in) opDir, integer(kind=8), intent(in) numPointsApply, integer(kind=8), dimension(numpointsapply), intent(in) applyPoints, integer(kind=4), intent(in) stencilSize, real(kind=8), dimension(stencilsize), intent(in) stencilWeights, integer(kind=4), dimension(stencilsize), intent(in) stencilOffsets, real(kind=8), dimension(numpointsbuffer), intent(in) U, real(kind=8), dimension(numpointsbuffer), intent(out) dU)
applysinglestencil applies an operator by applying a given stencil to the specified points applysinglestencil is a single-stencil method which operates on the given points The stencil and operand are given as flat, primitive arrays, with supporting data to indicate the size of the data structures. An additional array of points is given which indicates the points on which to operate. This single-stencil method loops through all the specified points and applies the stencil to each. applyoperatorBLOBS - blobbed method cartoon
Parameters:
numDim indicates the number of dimensions for the input data (dimSizes,opInterval)
dimSizes indicates the number of points in each dimension [Nx Ny Nz]
numComponents indicates the number of components in the input/output data (U,dU)
numPointsBuffer indicates the total number of points Nx*Ny*Nz
opDir indicates in which direction the operator will be applied [X=1 | Y=2 | Z=3]
numPointsApply total number of points in the stencilPoints array (needed for C/Fortran interface)
applyPoints array of size (numPointsApply) indicating the points to which to apply the stencil
stencilSize number of stencil weights
stencilWeights array of size (stencilSize) which contains the weights for all the stencils in the stencilset
stencilOffsets array of size (stencilSize) which indicates the offsets from the considered point to the point where each weight is applied
U the data on which to operate
dU where to stuff the result
Definition at line 383 of file Operators.f90.
Referenced by applyoperatorblobs().
Author
Generated automatically by Doxygen for JustKernels from the source code.