.TH "RKKernels.H" 3 "Fri Apr 10 2020" "Version 1.0" "JustKernels" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RKKernels.H \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'FC\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBFC_MODULE\fP (rungekutta, rk4sum, RUNGEKUTTA, RK4SUM)(int *"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void FC_MODULE (rungekutta, rk4sum, RUNGEKUTTA, RK4SUM)"

.SH "Author"
.PP 
Generated automatically by Doxygen for JustKernels from the source code\&.
