roe
NAME
roe -
SYNOPSIS
Functions/Subroutines
subroutine pointroestate2 (numDim, numScalar, uLeft, dvLeft, uRight, dvRight, uRoe)
subroutine pointroestate (numDim, numScalar, uIn, dvIn, uOut, dvOut, uRoe, dvRoe, dv2Roe)
subroutine cross_product1 (v1, v2, y)
subroutine eigenmatrices (numDim, numScalars, qRoe, dvRoe, dp, soundSpeed, gridScale, metricEigenVectors, Pfor, Pinv, lambda)
subroutine form_roe_state (ND, numScalars, u_in, u_out, gamma, norm, uRoe, dvRoe, ucon, cRoe, theta)
subroutine form_roe_matrices (ND, u_in, u_out, gamma, norm, tmat, tinv, lambda)
subroutine limitdp (numDim, numScalars, qIn, dvIn, qOut, dvOut, qRoe, dvRoe, dpRoe)
subroutine original_frontmatter (ND, numScalars, u_in, u_out, p_in, p_out, uRoe, dvRoe, gamma, norm, MT1, alpha, beta, theta, phi2, b1, b2, metricEV)
Function/Subroutine Documentation
subroutine roe::cross_product1 (real(kind=8), dimension(3) v1, real(kind=8), dimension(3) v2, real(kind=8), dimension(3) y)
Definition at line 167 of file Roe.f90.
subroutine roe::eigenmatrices (integer(kind=4), intent(in) numDim, integer(kind=4), intent(in) numScalars, real(kind=8), dimension(numdim+2+numscalars), intent(in) qRoe, real(kind=8), dimension(numdim+2), intent(in) dvRoe, real(kind=8), dimension(2+numscalars), intent(in) dp, real(kind=8), intent(in) soundSpeed, real(kind=8), intent(in) gridScale, real(kind=8), dimension(numdim*numdim), intent(in) metricEigenVectors, real(kind=8), dimension(numdim+2+numscalars,numdim+2+numscalars), intent(out) Pfor, real(kind=8), dimension(numdim+2+numscalars,numdim+2+numscalars), intent(out) Pinv, real(kind=8), dimension(numdim+2+numscalars,numdim+2+numscalars), intent(out) lambda)
Definition at line 187 of file Roe.f90.
References metricops::pointeigenvectorsgs().
Referenced by satutil::farfield(), satutil::noslip_isothermal(), and satutil::slip_adiabatic().
subroutine roe::form_roe_matrices (integer(kind=4) ND, real(8), dimension(nd+2) u_in, real(8), dimension(nd+2) u_out, real(8) gamma, real(8), dimension(nd) norm, real(8), dimension(nd+2,nd+2) tmat, real(8), dimension(nd+2,nd+2) tinv, real(8), dimension(nd+2,nd+2) lambda)
Definition at line 524 of file Roe.f90.
subroutine roe::form_roe_state (integer(4), intent(in) ND, integer(4), intent(in) numScalars, real(8), dimension(nd+2), intent(in) u_in, real(8), dimension(nd+2), intent(in) u_out, real(8), intent(in) gamma, real(8), dimension(nd), intent(in) norm, real(8), dimension(nd+2), intent(out) uRoe, real(8), dimension(nd+3), intent(out) dvRoe, real(8), intent(out) ucon, real(8), intent(out) cRoe, real(8), intent(out) theta)
Definition at line 440 of file Roe.f90.
subroutine roe::limitdp (integer(4), intent(in) numDim, integer(4), intent(in) numScalars, real(8), dimension(numdim+2+numscalars), intent(in) qIn, real(8), dimension(numdim+2), intent(in) dvIn, real(8), dimension(numdim+2+numscalars), intent(in) qOut, real(8), dimension(numdim+2), intent(in) dvOut, real(8), dimension(numdim+2+numscalars), intent(in) qRoe, real(8), dimension(numdim+2), intent(in) dvRoe, real(8), dimension(numscalars+2), intent(inout) dpRoe)
Definition at line 733 of file Roe.f90.
subroutine roe::original_frontmatter (integer(4) ND, integer(4) numScalars, real(8), dimension(:), pointer u_in, real(8), dimension(:), pointer u_out, real(8) p_in, real(8) p_out, real(8), dimension(nd+2+numscalars) uRoe, real(8), dimension(nd+2) dvRoe, real(8) gamma, real(8), dimension(:), pointer norm, real(8), dimension(:), pointer MT1, real(8) alpha, real(8) beta, real(8) theta, real(8) phi2, real(8) b1, real(8) b2, real(8), dimension(:), pointer metricEV)
Definition at line 795 of file Roe.f90.
subroutine roe::pointroestate (integer(kind=4), intent(in) numDim, integer(kind=4), intent(in) numScalar, real(kind=8), dimension(numdim+2+numscalar), intent(in), target uIn, real(kind=8), dimension(numdim+2), intent(in), target dvIn, real(kind=8), dimension(numdim+2+numscalar), intent(in), target uOut, real(kind=8), dimension(numdim+2), intent(in), target dvOut, real(kind=8), dimension(numdim+2+numscalar), intent(inout), target uRoe, real(kind=8), dimension(numdim+2), intent(inout), target dvRoe, real(kind=8), dimension(3), intent(inout), target dv2Roe)
Definition at line 88 of file Roe.f90.
subroutine roe::pointroestate2 (integer(kind=4), intent(in) numDim, integer(kind=4), intent(in) numScalar, real(kind=8), dimension(numdim+2+numscalar), intent(in), target uLeft, real(kind=8), dimension(numdim+2), intent(in), target dvLeft, real(kind=8), dimension(numdim+2+numscalar), intent(in), target uRight, real(kind=8), dimension(numdim+2), intent(in), target dvRight, real(kind=8), dimension(numdim+2+numscalar), intent(inout), target uRoe)
Definition at line 20 of file Roe.f90.
Referenced by satutil::farfield(), satutil::noslip_isothermal(), and satutil::slip_adiabatic().
Author
Generated automatically by Doxygen for JustKernels from the source code.