.TH "roe" 3 "Fri Apr 10 2020" "Version 1.0" "JustKernels" \" -*- nroff -*-
.ad l
.nh
.SH NAME
roe \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBpointroestate2\fP (\fBnumDim\fP, \fBnumScalar\fP, \fBuLeft\fP, dvLeft, \fBuRight\fP, dvRight, \fBuRoe\fP)"
.br
.ti -1c
.RI "subroutine \fBpointroestate\fP (\fBnumDim\fP, \fBnumScalar\fP, \fBuIn\fP, \fBdvIn\fP, \fBuOut\fP, \fBdvOut\fP, \fBuRoe\fP, \fBdvRoe\fP, \fBdv2Roe\fP)"
.br
.ti -1c
.RI "subroutine \fBcross_product1\fP (v1, v2, \fBy\fP)"
.br
.ti -1c
.RI "subroutine \fBeigenmatrices\fP (\fBnumDim\fP, \fBnumScalars\fP, \fBqRoe\fP, \fBdvRoe\fP, \fBdp\fP, \fBsoundSpeed\fP, gridScale, \fBmetricEigenVectors\fP, \fBPfor\fP, \fBPinv\fP, \fBlambda\fP)"
.br
.ti -1c
.RI "subroutine \fBform_roe_state\fP (ND, \fBnumScalars\fP, \fBu_in\fP, \fBu_out\fP, \fBgamma\fP, \fBnorm\fP, \fBuRoe\fP, \fBdvRoe\fP, ucon, \fBcRoe\fP, \fBtheta\fP)"
.br
.ti -1c
.RI "subroutine \fBform_roe_matrices\fP (ND, \fBu_in\fP, \fBu_out\fP, \fBgamma\fP, \fBnorm\fP, \fBtmat\fP, \fBtinv\fP, \fBlambda\fP)"
.br
.ti -1c
.RI "subroutine \fBlimitdp\fP (\fBnumDim\fP, \fBnumScalars\fP, qIn, \fBdvIn\fP, qOut, \fBdvOut\fP, \fBqRoe\fP, \fBdvRoe\fP, dpRoe)"
.br
.ti -1c
.RI "subroutine \fBoriginal_frontmatter\fP (ND, \fBnumScalars\fP, \fBu_in\fP, \fBu_out\fP, p_in, p_out, \fBuRoe\fP, \fBdvRoe\fP, \fBgamma\fP, \fBnorm\fP, MT1, alpha, beta, \fBtheta\fP, phi2, b1, b2, metricEV)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine roe::cross_product1 (real(kind=8), dimension(3) v1, real(kind=8), dimension(3) v2, real(kind=8), dimension(3) y)"

.PP
Definition at line 167 of file Roe\&.f90\&.
.SS "subroutine roe::eigenmatrices (integer(kind=4), intent(in) numDim, integer(kind=4), intent(in) numScalars, real(kind=8), dimension(numdim+2+numscalars), intent(in) qRoe, real(kind=8), dimension(numdim+2), intent(in) dvRoe, real(kind=8), dimension(2+numscalars), intent(in) dp, real(kind=8), intent(in) soundSpeed, real(kind=8), intent(in) gridScale, real(kind=8), dimension(numdim*numdim), intent(in) metricEigenVectors, real(kind=8), dimension(numdim+2+numscalars,numdim+2+numscalars), intent(out) Pfor, real(kind=8), dimension(numdim+2+numscalars,numdim+2+numscalars), intent(out) Pinv, real(kind=8), dimension(numdim+2+numscalars,numdim+2+numscalars), intent(out) lambda)"

.PP
Definition at line 187 of file Roe\&.f90\&.
.PP
References metricops::pointeigenvectorsgs()\&.
.PP
Referenced by satutil::farfield(), satutil::noslip_isothermal(), and satutil::slip_adiabatic()\&.
.SS "subroutine roe::form_roe_matrices (integer(kind=4) ND, real(8), dimension(nd+2) u_in, real(8), dimension(nd+2) u_out, real(8) gamma, real(8), dimension(nd) norm, real(8), dimension(nd+2,nd+2) tmat, real(8), dimension(nd+2,nd+2) tinv, real(8), dimension(nd+2,nd+2) lambda)"

.PP
Definition at line 524 of file Roe\&.f90\&.
.SS "subroutine roe::form_roe_state (integer(4), intent(in) ND, integer(4), intent(in) numScalars, real(8), dimension(nd+2), intent(in) u_in, real(8), dimension(nd+2), intent(in) u_out, real(8), intent(in) gamma, real(8), dimension(nd), intent(in) norm, real(8), dimension(nd+2), intent(out) uRoe, real(8), dimension(nd+3), intent(out) dvRoe, real(8), intent(out) ucon, real(8), intent(out) cRoe, real(8), intent(out) theta)"

.PP
Definition at line 440 of file Roe\&.f90\&.
.SS "subroutine roe::limitdp (integer(4), intent(in) numDim, integer(4), intent(in) numScalars, real(8), dimension(numdim+2+numscalars), intent(in) qIn, real(8), dimension(numdim+2), intent(in) dvIn, real(8), dimension(numdim+2+numscalars), intent(in) qOut, real(8), dimension(numdim+2), intent(in) dvOut, real(8), dimension(numdim+2+numscalars), intent(in) qRoe, real(8), dimension(numdim+2), intent(in) dvRoe, real(8), dimension(numscalars+2), intent(inout) dpRoe)"

.PP
Definition at line 733 of file Roe\&.f90\&.
.SS "subroutine roe::original_frontmatter (integer(4) ND, integer(4) numScalars, real(8), dimension(:), pointer u_in, real(8), dimension(:), pointer u_out, real(8) p_in, real(8) p_out, real(8), dimension(nd+2+numscalars) uRoe, real(8), dimension(nd+2) dvRoe, real(8) gamma, real(8), dimension(:), pointer norm, real(8), dimension(:), pointer MT1, real(8) alpha, real(8) beta, real(8) theta, real(8) phi2, real(8) b1, real(8) b2, real(8), dimension(:), pointer metricEV)"

.PP
Definition at line 795 of file Roe\&.f90\&.
.SS "subroutine roe::pointroestate (integer(kind=4), intent(in) numDim, integer(kind=4), intent(in) numScalar, real(kind=8), dimension(numdim+2+numscalar), intent(in), target uIn, real(kind=8), dimension(numdim+2), intent(in), target dvIn, real(kind=8), dimension(numdim+2+numscalar), intent(in), target uOut, real(kind=8), dimension(numdim+2), intent(in), target dvOut, real(kind=8), dimension(numdim+2+numscalar), intent(inout), target uRoe, real(kind=8), dimension(numdim+2), intent(inout), target dvRoe, real(kind=8), dimension(3), intent(inout), target dv2Roe)"

.PP
Definition at line 88 of file Roe\&.f90\&.
.SS "subroutine roe::pointroestate2 (integer(kind=4), intent(in) numDim, integer(kind=4), intent(in) numScalar, real(kind=8), dimension(numdim+2+numscalar), intent(in), target uLeft, real(kind=8), dimension(numdim+2), intent(in), target dvLeft, real(kind=8), dimension(numdim+2+numscalar), intent(in), target uRight, real(kind=8), dimension(numdim+2), intent(in), target dvRight, real(kind=8), dimension(numdim+2+numscalar), intent(inout), target uRoe)"

.PP
Definition at line 20 of file Roe\&.f90\&.
.PP
Referenced by satutil::farfield(), satutil::noslip_isothermal(), and satutil::slip_adiabatic()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for JustKernels from the source code\&.
