satutil
NAME
satutil -
SYNOPSIS
Functions/Subroutines
subroutine farfield (eosInfo, eosNonDimen, eosGasParams, numDim, bufferSizes, numPointsBuffer, patchNormalDir, patchSizes, numPointsPatch, numPatchPointsOp, patchPointsOp, gridType, gridMetric, jacobianDeterminant, bcParams, gasParams, rhoBuffer, rhoVBuffer, rhoEBuffer, viscousFluxBuffer, numscalar, scalarBuffer, rhoRHS, rhoVRHS, rhoERHS, scalarRHS, rhoTarget, rhoVTarget, rhoETarget, scalarTarget)
subroutine slip_adiabatic (eosInfo, eosNonDimen, eosGasParams, numDim, bufferSizes, numPointsBuffer, patchNormalDir, sconn, patchSizes, numPointsPatch, numPatchPointsOp, patchPointsOp, gridType, gridMetric, jacobianDeterminant, bcParams, gasParams, rhoBuffer, rhoVBuffer, rhoEBuffer, numscalar, scalarBuffer, scalarGrad, rhoRHS, rhoVRHS, rhoERHS, scalarRHS, rhoTarget, rhoVTarget, rhoETarget, scalarTarget)
subroutine noslip_isothermal (eosInfo, eosNonDimen, eosGasParams, numDim, bufferSizes, numPointsBuffer, patchNormalDir, sconn, patchSizes, numPointsPatch, numPatchPointsOp, patchPointsOp, gridType, gridMetric, jacobianDeterminant, bcParams, gasParams, rhoBuffer, rhoVBuffer, rhoEBuffer, numscalar, scalarBuffer, scalarGrad, rhoRHS, rhoVRHS, rhoERHS, scalarRHS, rhoTarget, rhoVTarget, rhoETarget, scalarTarget, muBuffer, lambdaBuffer)
subroutine dissipationweight (numDim, bufferSize, numPoints, bufferInterval, sigmaDissipation, sigmaDilatation, dilatationRamp, dilatationCutoff, divV, sigmaDiss)
Function/Subroutine Documentation
subroutine satutil::dissipationweight (integer(kind=4), intent(in) numDim, integer(kind=8), dimension(numdim), intent(in) bufferSize, integer(kind=8), intent(in) numPoints, integer(kind=8), dimension(2*numdim), intent(in) bufferInterval, real(kind=8), intent(in) sigmaDissipation, real(kind=8), intent(in) sigmaDilatation, real(kind=8), intent(in) dilatationRamp, real(kind=8), intent(in) dilatationCutoff, real(kind=8), dimension(numpoints), intent(in) divV, real(kind=8), dimension(numpoints), intent(out) sigmaDiss)
Definition at line 1060 of file SATUtil.f90.
subroutine satutil::farfield (integer(kind=8), dimension(numgasinfos) eosInfo, real(kind=8), dimension(numnondimens) eosNonDimen, real(kind=8), dimension(numgasparams*(numscalar+1)) eosGasParams, integer(kind=4) numDim, integer(kind=8), dimension(numdim) bufferSizes, integer(kind=8) numPointsBuffer, integer(kind=4) patchNormalDir, integer(kind=8), dimension(numdim) patchSizes, integer(kind=8) numPointsPatch, integer(kind=8) numPatchPointsOp, integer(kind=8), dimension(numpatchpointsop) patchPointsOp, integer(kind=4) gridType, real(kind=8), dimension(numdim*numdim*numpointsbuffer) gridMetric, real(kind=8), dimension(numpointsbuffer) jacobianDeterminant, real(kind=8), dimension(3) bcParams, real(kind=8), dimension(5) gasParams, real(kind=8), dimension(numpointsbuffer) rhoBuffer, real(kind=8), dimension(numdim*numpointsbuffer) rhoVBuffer, real(kind=8), dimension(numpointsbuffer) rhoEBuffer, real(kind=8), dimension((numdim+2+numscalar)*numpointsbuffer) viscousFluxBuffer, integer(kind=4) numscalar, real(kind=8), dimension(numscalar*numpointsbuffer) scalarBuffer, real(kind=8), dimension(numpointsbuffer) rhoRHS, real(kind=8), dimension(numdim*numpointsbuffer) rhoVRHS, real(kind=8), dimension(numpointsbuffer) rhoERHS, real(kind=8), dimension(numscalar*numpointsbuffer) scalarRHS, real(kind=8), dimension(numpointsbuffer) rhoTarget, real(kind=8), dimension(numdim*numpointsbuffer) rhoVTarget, real(kind=8), dimension(numpointsbuffer) rhoETarget, real(kind=8), dimension(numscalar*numpointsbuffer) scalarTarget)
Note:
Scalar diffusion not yet done [mtc]
Definition at line 19 of file SATUtil.f90.
References metricops::boundarypointmetric(), roe::eigenmatrices(), metricops::pointeigenvectors(), roe::pointroestate2(), and grid::rectilinear.
subroutine satutil::noslip_isothermal (integer(kind=8), dimension(numgasinfos) eosInfo, real(kind=8), dimension(numnondimens) eosNonDimen, real(kind=8), dimension(numgasparams*(numscalar+1)) eosGasParams, integer(kind=4) numDim, integer(kind=8), dimension(numdim) bufferSizes, integer(kind=8) numPointsBuffer, integer(kind=4) patchNormalDir, integer(kind=4), dimension(numpointsbuffer) sconn, integer(kind=8), dimension(numdim) patchSizes, integer(kind=8) numPointsPatch, integer(kind=8) numPatchPointsOp, integer(kind=8), dimension(numpatchpointsop) patchPointsOp, integer(kind=4) gridType, real(kind=8), dimension(numdim*numdim*numpointsbuffer) gridMetric, real(kind=8), dimension(numpointsbuffer) jacobianDeterminant, real(kind=8), dimension(4) bcParams, real(kind=8), dimension(6) gasParams, real(kind=8), dimension(numpointsbuffer) rhoBuffer, real(kind=8), dimension(numdim*numpointsbuffer) rhoVBuffer, real(kind=8), dimension(numpointsbuffer) rhoEBuffer, integer(kind=4) numscalar, real(kind=8), dimension(numscalar*numpointsbuffer) scalarBuffer, real(kind=8), dimension(numscalar*numdim*numpointsbuffer) scalarGrad, real(kind=8), dimension(numpointsbuffer) rhoRHS, real(kind=8), dimension(numdim*numpointsbuffer) rhoVRHS, real(kind=8), dimension(numpointsbuffer) rhoERHS, real(kind=8), dimension(numscalar*numpointsbuffer) scalarRHS, real(kind=8), dimension(numpointsbuffer) rhoTarget, real(kind=8), dimension(numdim*numpointsbuffer) rhoVTarget, real(kind=8), dimension(numpointsbuffer) rhoETarget, real(kind=8), dimension(numscalar*numpointsbuffer) scalarTarget, real(kind=8), dimension(numpointsbuffer) muBuffer, real(kind=8), dimension(numpointsbuffer) lambdaBuffer)
Definition at line 664 of file SATUtil.f90.
References metricops::boundarypointmetric(), roe::eigenmatrices(), metricops::pointeigenvectors(), roe::pointroestate2(), and grid::rectilinear.
subroutine satutil::slip_adiabatic (integer(kind=8), dimension(numgasinfos) eosInfo, real(kind=8), dimension(numnondimens) eosNonDimen, real(kind=8), dimension(numgasparams*(numscalar+1)) eosGasParams, integer(kind=4) numDim, integer(kind=8), dimension(numdim) bufferSizes, integer(kind=8) numPointsBuffer, integer(kind=4) patchNormalDir, integer(kind=4), dimension(numpointsbuffer) sconn, integer(kind=8), dimension(numdim) patchSizes, integer(kind=8) numPointsPatch, integer(kind=8) numPatchPointsOp, integer(kind=8), dimension(numpatchpointsop) patchPointsOp, integer(kind=4) gridType, real(kind=8), dimension(numdim*numdim*numpointsbuffer) gridMetric, real(kind=8), dimension(numpointsbuffer) jacobianDeterminant, real(kind=8), dimension(3) bcParams, real(kind=8), dimension(5) gasParams, real(kind=8), dimension(numpointsbuffer) rhoBuffer, real(kind=8), dimension(numdim*numpointsbuffer) rhoVBuffer, real(kind=8), dimension(numpointsbuffer) rhoEBuffer, integer(kind=4) numscalar, real(kind=8), dimension(numscalar*numpointsbuffer) scalarBuffer, real(kind=8), dimension(numscalar*numdim*numpointsbuffer) scalarGrad, real(kind=8), dimension(numpointsbuffer) rhoRHS, real(kind=8), dimension(numdim*numpointsbuffer) rhoVRHS, real(kind=8), dimension(numpointsbuffer) rhoERHS, real(kind=8), dimension(numscalar*numpointsbuffer) scalarRHS, real(kind=8), dimension(numpointsbuffer) rhoTarget, real(kind=8), dimension(numdim*numpointsbuffer) rhoVTarget, real(kind=8), dimension(numpointsbuffer) rhoETarget, real(kind=8), dimension(numscalar*numpointsbuffer) scalarTarget)
Todo
add viscous contribution for SAT_SLIP_ADIABATIC
Definition at line 349 of file SATUtil.f90.
References metricops::boundarypointmetric(), roe::eigenmatrices(), metricops::pointeigenvectors(), roe::pointroestate2(), and grid::rectilinear.
Author
Generated automatically by Doxygen for JustKernels from the source code.