simple
NAME
simple -
SYNOPSIS
Functions/Subroutines
subroutine yaxpy (numDim, numPoints, bufferSize, bufferInterval, a, X, Y)
YAXPY point-wise operator performing Y = aX + Y (scalar a)
subroutine zaxpy (numDim, numPoints, bufferSize, bufferInterval, a, X, Y, Z)
ZAXPY point-wise operator performing Z = aX + Y (scalar a)
subroutine zaxpby (numDim, numPoints, bufferSize, bufferInterval, a, b, X, Y, Z)
ZAXPBY point-wise operator performing Z = aX + bY (scalar a,b)
subroutine xaxm1 (numDim, numPoints, bufferSize, bufferInterval, a, X)
XAXM1 point-wise operator performing X = a/X (scalar a)
subroutine xam1x (numDim, numPoints, bufferSize, bufferInterval, a, X)
XAM1X point-wise operator performing X = X/a (scalar a)
subroutine yaxpby (numDim, numPoints, bufferSize, bufferInterval, a, b, X, Y)
YAXPBY point-wise operator performing Y = aX + bY (scalar a,b)
subroutine yax (numDim, numPoints, bufferSize, bufferInterval, a, X, Y)
YAX point-wise operator performing Y = aX (scalar a)
subroutine zxym1 (numDim, numPoints, bufferSize, bufferInterval, X, Y, Z)
ZXYM1 point-wise operator performing Z = X/Y (all vectors)
subroutine zxy (numDim, numPoints, bufferSize, bufferInterval, X, Y, Z)
ZXY point-wise operator performing Z = XY (all vectors)
subroutine zaxy (numDim, numPoints, bufferSize, bufferInterval, a, X, Y, Z)
ZAXY point-wise operator performing Z = aXY (scalar a, vectors X,Y)
subroutine yxy (numDim, numPoints, bufferSize, bufferInterval, X, Y)
YXY point-wise operator performing Y = XY (all vectors)
subroutine zwxpy (numDim, numPoints, bufferSize, bufferInterval, W, X, Y, Z)
ZWXPY point-wise operator performing Z = WX + Y, where all are vectors.
subroutine ywxpy (numDim, numPoints, bufferSize, bufferInterval, W, X, Y)
YWXPY point-wise operator performing Y = WX + Y, where all are vectors.
subroutine zawpxy (numDim, numPoints, bufferSize, bufferInterval, a, W, X, Y, Z)
ZAWPXY point-wise operator performing Z = aW + XY.
subroutine zvwpxy (numDim, numPoints, bufferSize, bufferInterval, V, W, X, Y, Z)
ZVWPXY point-wise operator performing Z = VW + XY.
subroutine zwmxpy (numDim, numPoints, bufferSize, bufferInterval, W, X, Y, Z)
ZWMXPY point-wise operator performing Z = W(X+Y) where all are vectors.
subroutine zxdoty (numDim, numPoints, bufferSize, bufferInterval, numComponents, X, Y, Z)
ZXDOTY numComponents-vector inner product Z = X * Y.
subroutine xax (numDim, numPoints, bufferSize, bufferInterval, a, X)
XAX point-wise operator performing X = aX (scalar a)
subroutine assignmentyx (numDim, numPoints, bufferSize, bufferInterval, X, Y)
ASSIGNMENTYX point-wise operator performing Y = X.
subroutine assignmentxa (numDim, numPoints, bufferSize, bufferInterval, a, X)
ASSIGNMENTXA point-wise operator performing X = scalar a.
subroutine assignmentyabsx (numDim, numPoints, bufferSize, bufferInterval, X, Y)
ASSIGNMENTYABSX point-wise operator performing X = scalar a.
subroutine veclen (numDim, numPoints, bufferSize, bufferInterval, numComp, V, lenV)
VECLEN point-wise operator returning the length of a numComp-dimensional vector.
subroutine yaxm1 (numDim, numPoints, bufferSize, bufferInterval, a, X, Y)
YAXM1 point-wise operator performing Y = a/X (scalar a)
subroutine vasupv (numDim, numPoints, bufferSize, bufferInterval, a, S, U, V)
VASUPV point-wise operator performing V = V + aW where a is a constant scalar, S is a scalar field, and V and W are vectors with numDim components.
subroutine yassmwdotupy (numDim, numPoints, bufferSize, bufferInterval, a, S1, S2, W, U, Y)
YASSMWDOTUPY point-wise operator performing Y = Y + a*(S1+S2)*(W dot U) where W, and U are vector fields with numDim components, and a is a constant scalar, and S1, S2, and Y are scalar fields.
subroutine yasmwdotupy (numDim, numPoints, bufferSize, bufferInterval, a, S, W, U, Y)
YASMWDOTUPY point-wise operator performing Y = Y + a*S*(W dot U) where W, and U are vector fields with numDim components, and a is a constant scalar, and S,Y are scalar fields.
subroutine yavdotwpy (numDim, numPoints, bufferSize, bufferInterval, a, V, W, Y)
YAVDOTWPY point-wise operator performing Y = Y + a(V dot W) where Y is a scalar field, a is a constant scalar, V and W are vector fields with numDim components.
Function/Subroutine Documentation
subroutine simple::assignmentxa (integer(kind=4), intent(in) numDim, integer(kind=8), intent(in) numPoints, integer(kind=8), dimension(numdim), intent(in) bufferSize, integer(kind=8), dimension(2*numdim), intent(in) bufferInterval, real(kind=8), intent(in) a, real(kind=8), dimension(numpoints), intent(inout) X)
ASSIGNMENTXA point-wise operator performing X = scalar a.
Definition at line 1091 of file Simple.f90.
Referenced by metricops::alphaweight(), metricops::alphaweight2(), grid::computecurvilineargridmetrics(), metricops::gradijktogradxyz(), viscid::strongflux1d(), and zxdoty().
subroutine simple::assignmentyabsx (integer(kind=4), intent(in) numDim, integer(kind=8), intent(in) numPoints, integer(kind=8), dimension(numdim), intent(in) bufferSize, integer(kind=8), dimension(2*numdim), intent(in) bufferInterval, real(kind=8), dimension(numpoints), intent(in) X, real(kind=8), dimension(numpoints), intent(out) Y)
ASSIGNMENTYABSX point-wise operator performing X = scalar a.
Definition at line 1144 of file Simple.f90.
Referenced by metricops::alphaweight(), and metricops::alphaweight2().
subroutine simple::assignmentyx (integer(kind=4), intent(in) numDim, integer(kind=8), intent(in) numPoints, integer(kind=8), dimension(numdim), intent(in) bufferSize, integer(kind=8), dimension(2*numdim), intent(in) bufferInterval, real(kind=8), dimension(numpoints), intent(in) X, real(kind=8), dimension(numpoints), intent(inout) Y)
ASSIGNMENTYX point-wise operator performing Y = X.
Definition at line 1039 of file Simple.f90.
Referenced by grid::computecurvilineargridmetrics().
subroutine simple::vasupv (integer(kind=4), intent(in) numDim, integer(kind=8), intent(in) numPoints, integer(kind=8), dimension(numdim), intent(in) bufferSize, integer(kind=8), dimension(2*numdim), intent(in) bufferInterval, real(kind=8), intent(in) a, real(kind=8), dimension(numpoints), intent(in) S, real(kind=8), dimension(numdim*numpoints), intent(in) U, real(kind=8), dimension(numdim*numpoints), intent(inout) V)
VASUPV point-wise operator performing V = V + aW where a is a constant scalar, S is a scalar field, and V and W are vectors with numDim components.
Definition at line 1320 of file Simple.f90.
subroutine simple::veclen (integer(kind=4), intent(in) numDim, integer(kind=8), intent(in) numPoints, integer(kind=8), dimension(numdim), intent(in) bufferSize, integer(kind=8), dimension(2*numdim), intent(in) bufferInterval, integer(kind=4), intent(in) numComp, real(kind=8), dimension(numcomp*numpoints), intent(in) V, real(kind=8), dimension(numpoints), intent(out) lenV)
VECLEN point-wise operator returning the length of a numComp-dimensional vector.
Definition at line 1197 of file Simple.f90.
Referenced by metricops::alphaweight(), and metricops::alphaweight2().
subroutine simple::xam1x (integer(kind=4), intent(in) numDim, integer(kind=8), intent(in) numPoints, integer(kind=8), dimension(numdim), intent(in) bufferSize, integer(kind=8), dimension(2*numdim), intent(in) bufferInterval, real(kind=8), intent(in) a, real(kind=8), dimension(numpoints), intent(inout) X)
XAM1X point-wise operator performing X = X/a (scalar a)
Definition at line 214 of file Simple.f90.
subroutine simple::xax (integer(kind=4), intent(in) numDim, integer(kind=8), intent(in) numPoints, integer(kind=8), dimension(numdim), intent(in) bufferSize, integer(kind=8), dimension(2*numdim), intent(in) bufferInterval, real(kind=8), intent(in) a, real(kind=8), dimension(numpoints), intent(inout) X)
XAX point-wise operator performing X = aX (scalar a)
Definition at line 988 of file Simple.f90.
Referenced by metricops::ijkgradtoxyzdiv().
subroutine simple::xaxm1 (integer(kind=4), intent(in) numDim, integer(kind=8), intent(in) numPoints, integer(kind=8), dimension(numdim), intent(in) bufferSize, integer(kind=8), dimension(2*numdim), intent(in) bufferInterval, real(kind=8), intent(in) a, real(kind=8), dimension(numpoints), intent(inout) X)
XAXM1 point-wise operator performing X = a/X (scalar a)
Definition at line 162 of file Simple.f90.
subroutine simple::yasmwdotupy (integer(kind=4), intent(in) numDim, integer(kind=8), intent(in) numPoints, integer(kind=8), dimension(numdim), intent(in) bufferSize, integer(kind=8), dimension(2*numdim), intent(in) bufferInterval, real(kind=8), intent(in) a, real(kind=8), dimension(numpoints), intent(in) S, real(kind=8), dimension(numdim*numpoints), intent(in) W, real(kind=8), dimension(numdim*numpoints), intent(in) U, real(kind=8), dimension(numpoints), intent(inout) Y)
YASMWDOTUPY point-wise operator performing Y = Y + a*S*(W dot U) where W, and U are vector fields with numDim components, and a is a constant scalar, and S,Y are scalar fields.
Definition at line 1453 of file Simple.f90.
subroutine simple::yassmwdotupy (integer(kind=4), intent(in) numDim, integer(kind=8), intent(in) numPoints, integer(kind=8), dimension(numdim), intent(in) bufferSize, integer(kind=8), dimension(2*numdim), intent(in) bufferInterval, real(kind=8), intent(in) a, real(kind=8), dimension(numpoints), intent(in) S1, real(kind=8), dimension(numpoints), intent(in) S2, real(kind=8), dimension(numdim*numpoints), intent(in) W, real(kind=8), dimension(numdim*numpoints), intent(in) U, real(kind=8), dimension(numpoints), intent(inout) Y)
YASSMWDOTUPY point-wise operator performing Y = Y + a*(S1+S2)*(W dot U) where W, and U are vector fields with numDim components, and a is a constant scalar, and S1, S2, and Y are scalar fields.
Definition at line 1385 of file Simple.f90.
subroutine simple::yavdotwpy (integer(kind=4), intent(in) numDim, integer(kind=8), intent(in) numPoints, integer(kind=8), dimension(numdim), intent(in) bufferSize, integer(kind=8), dimension(2*numdim), intent(in) bufferInterval, real(kind=8), intent(in) a, real(kind=8), dimension(numdim*numpoints), intent(in) V, real(kind=8), dimension(numdim*numpoints), intent(in) W, real(kind=8), dimension(numpoints), intent(inout) Y)
YAVDOTWPY point-wise operator performing Y = Y + a(V dot W) where Y is a scalar field, a is a constant scalar, V and W are vector fields with numDim components.
Definition at line 1519 of file Simple.f90.
subroutine simple::yax (integer(kind=4), intent(in) numDim, integer(kind=8), intent(in) numPoints, integer(kind=8), dimension(numdim), intent(in) bufferSize, integer(kind=8), dimension(2*numdim), intent(in) bufferInterval, real(kind=8), intent(in) a, real(kind=8), dimension(numpoints), intent(in) X, real(kind=8), dimension(numpoints), intent(out) Y)
YAX point-wise operator performing Y = aX (scalar a)
Definition at line 318 of file Simple.f90.
Referenced by metricops::gradijktogradxyz(), viscid::scalarflux1d(), viscid::strongflux1d(), and metricops::vhatcomponent().
subroutine simple::yaxm1 (integer(kind=4), intent(in) numDim, integer(kind=8), intent(in) numPoints, integer(kind=8), dimension(numdim), intent(in) bufferSize, integer(kind=8), dimension(2*numdim), intent(in) bufferInterval, real(kind=8), intent(in) a, real(kind=8), dimension(numpoints), intent(inout) X, real(kind=8), dimension(numpoints), intent(inout) Y)
YAXM1 point-wise operator performing Y = a/X (scalar a)
Definition at line 1265 of file Simple.f90.
Referenced by grid::computecurvilineargridmetrics().
subroutine simple::yaxpby (integer(kind=4), intent(in) numDim, integer(kind=8), intent(in) numPoints, integer(kind=8), dimension(numdim), intent(in) bufferSize, integer(kind=8), dimension(2*numdim), intent(in) bufferInterval, real(kind=8), intent(in) a, real(kind=8), intent(in) b, real(kind=8), dimension(numpoints), intent(in) X, real(kind=8), dimension(numpoints), intent(inout) Y)
YAXPBY point-wise operator performing Y = aX + bY (scalar a,b)
Definition at line 267 of file Simple.f90.
subroutine simple::yaxpy (integer(kind=4), intent(in) numDim, integer(kind=8), intent(in) numPoints, integer(kind=8), dimension(numdim), intent(in) bufferSize, integer(kind=8), dimension(2*numdim), intent(in) bufferInterval, real(kind=8), intent(in) a, real(kind=8), dimension(numpoints), intent(in) X, real(kind=8), dimension(numpoints), intent(inout) Y)
YAXPY point-wise operator performing Y = aX + Y (scalar a)
Definition at line 9 of file Simple.f90.
Referenced by metricops::ijkgradtoxyzdiv().
subroutine simple::ywxpy (integer(kind=4), intent(in) numDim, integer(kind=8), intent(in) numPoints, integer(kind=8), dimension(numdim), intent(in) bufferSize, integer(kind=8), dimension(2*numdim), intent(in) bufferInterval, real(kind=8), dimension(numpoints), intent(in) W, real(kind=8), dimension(numpoints), intent(in) X, real(kind=8), dimension(numpoints), intent(inout) Y)
YWXPY point-wise operator performing Y = WX + Y, where all are vectors.
Definition at line 647 of file Simple.f90.
Referenced by metricops::gradijktogradxyz(), metricops::ijkgradtoxyzdiv(), and viscid::strongflux1d().
subroutine simple::yxy (integer(kind=4), intent(in) numDim, integer(kind=8), intent(in) numPoints, integer(kind=8), dimension(numdim), intent(in) bufferSize, integer(kind=8), dimension(2*numdim), intent(in) bufferInterval, real(kind=8), dimension(numpoints), intent(in) X, real(kind=8), dimension(numpoints), intent(inout) Y)
YXY point-wise operator performing Y = XY (all vectors)
Definition at line 543 of file Simple.f90.
Referenced by metricops::alphaweight2(), metricops::gradijktogradxyz(), and metricops::ijkgradtoxyzdiv().
subroutine simple::zawpxy (integer(kind=4), intent(in) numDim, integer(kind=8), intent(in) numPoints, integer(kind=8), dimension(numdim), intent(in) bufferSize, integer(kind=8), dimension(2*numdim), intent(in) bufferInterval, real(kind=8), intent(in) a, real(kind=8), dimension(numpoints), intent(in) W, real(kind=8), dimension(numpoints), intent(in) X, real(kind=8), dimension(numpoints), intent(in) Y, real(kind=8), dimension(numpoints), intent(out) Z)
ZAWPXY point-wise operator performing Z = aW + XY. ZAWPXY kernel performs Z = aW + XY with scalar a, contiguous input vectors W, X, and Y, and output vector Z. Operand arrays are contiguous of size numPoints. The kernel operates on the rectangular interval specified by bufferInterval. The shape of the input and output arrays are specified by bufferSize, which is an numDim - dimensional array that specifies the size in each of numDim dimesions.
Parameters:
numDim - const integer input specifies the number of dimensions of the input and output arrays
numPoints - const 64-bit integer input specifies the total size of the input and output arrays
bufferSize - const 64-bit integer array of size numDim specifies the size of the input and output arrays in each of numDim dimensions
bufferInterval - const 64-bit integer array of size 2 x numDim indicating the rectangular interval in which the kernel should operate; e.g. [ iStart iEnd jStart jEnd ]
a - const input double precision scalar
W - const double precision contiguous array of size numPoints
X - const double precision contiguous array of size numPoints
Y - const double precision contiguous array of size numPoints
Z - output double precision contiguous array of size numpoints
Definition at line 718 of file Simple.f90.
Referenced by euler::flux1d().
subroutine simple::zaxpby (integer(kind=4), intent(in) numDim, integer(kind=8), intent(in) numPoints, integer(kind=8), dimension(numdim), intent(in) bufferSize, integer(kind=8), dimension(2*numdim), intent(in) bufferInterval, real(kind=8), intent(in) a, real(kind=8), intent(in) b, real(kind=8), dimension(numpoints), intent(in) X, real(kind=8), dimension(numpoints), intent(in) Y, real(kind=8), dimension(numpoints), intent(out) Z)
ZAXPBY point-wise operator performing Z = aX + bY (scalar a,b)
Definition at line 111 of file Simple.f90.
subroutine simple::zaxpy (integer(kind=4), intent(in) numDim, integer(kind=8), intent(in) numPoints, integer(kind=8), dimension(numdim), intent(in) bufferSize, integer(kind=8), dimension(2*numdim), intent(in) bufferInterval, real(kind=8), intent(in) a, real(kind=8), dimension(numpoints), intent(in) X, real(kind=8), dimension(numpoints), intent(in) Y, real(kind=8), dimension(numpoints), intent(out) Z)
ZAXPY point-wise operator performing Z = aX + Y (scalar a)
Definition at line 60 of file Simple.f90.
subroutine simple::zaxy (integer(kind=4), intent(in) numDim, integer(kind=8), intent(in) numPoints, integer(kind=8), dimension(numdim), intent(in) bufferSize, integer(kind=8), dimension(2*numdim), intent(in) bufferInterval, real(kind=8), intent(in) a, real(kind=8), dimension(numpoints), intent(in) X, real(kind=8), dimension(numpoints), intent(in) Y, real(kind=8), dimension(numpoints), intent(out) Z)
ZAXY point-wise operator performing Z = aXY (scalar a, vectors X,Y)
Definition at line 490 of file Simple.f90.
subroutine simple::zvwpxy (integer(kind=4), intent(in) numDim, integer(kind=8), intent(in) numPoints, integer(kind=8), dimension(numdim), intent(in) bufferSize, integer(kind=8), dimension(2*numdim), intent(in) bufferInterval, real(kind=8), dimension(numpoints), intent(in) V, real(kind=8), dimension(numpoints), intent(in) W, real(kind=8), dimension(numpoints), intent(in) X, real(kind=8), dimension(numpoints), intent(in) Y, real(kind=8), dimension(numpoints), intent(out) Z)
ZVWPXY point-wise operator performing Z = VW + XY. ZVWPXY kernel performs Z = VW + XY with contiguous double precision input arrays V, W, X, and Y, and output array Z. Operand arrays are contiguous of size numPoints. The kernel operates on the rectangular interval specified by bufferInterval. The shape of the input and output arrays are specified by bufferSize, which is an numDim - dimensional array that specifies the size in each of numDim dimesions.
Parameters:
numDim - const integer input specifies the number of dimensions of the input and output arrays
numPoints - const 64-bit integer input specifies the total size of the input and output arrays
bufferSize - const 64-bit integer array of size numDim specifies the size of the input and output arrays in each of numDim dimensions
bufferInterval - const 64-bit integer array of size 2 x numDim indicating the rectangular interval in which the kernel should operate; e.g. [ iStart iEnd jStart jEnd ]
V - input const double precision contiguous array of size numPoints
W - input const double precision contiguous array of size numPoints
X - input const double precision contiguous array of size numPoints
Y - input const double precision contiguous array of size numPoints
Z - output double precision contiguous array of size numpoints
Definition at line 791 of file Simple.f90.
Referenced by euler::flux1d().
subroutine simple::zwmxpy (integer(kind=4), intent(in) numDim, integer(kind=8), intent(in) numPoints, integer(kind=8), dimension(numdim), intent(in) bufferSize, integer(kind=8), dimension(2*numdim), intent(in) bufferInterval, real(kind=8), dimension(numpoints), intent(in) W, real(kind=8), dimension(numpoints), intent(in) X, real(kind=8), dimension(numpoints), intent(in) Y, real(kind=8), dimension(numpoints), intent(out) Z)
ZWMXPY point-wise operator performing Z = W(X+Y) where all are vectors. ZVWPXY kernel performs Z = W(X+Y) with contiguous double precision input arrays W, X, and Y, and output array Z. Operand arrays are contiguous of size numPoints. The kernel operates on the rectangular interval specified by bufferInterval. The shape of the input and output arrays are specified by bufferSize, which is an numDim - dimensional array that specifies the size in each of numDim dimesions.
Parameters:
numDim - const integer input specifies the number of dimensions of the input and output arrays
numPoints - const 64-bit integer input specifies the total size of the input and output arrays
bufferSize - const 64-bit integer array of size numDim specifies the size of the input and output arrays in each of numDim dimensions
bufferInterval - const 64-bit integer array of size 2 x numDim indicating the rectangular interval in which the kernel should operate; e.g. [ iStart iEnd jStart jEnd ]
W - input const double precision contiguous array of size numPoints
X - input const double precision contiguous array of size numPoints
Y - input const double precision contiguous array of size numPoints
Z - output double precision contiguous array of size numpoints
Definition at line 865 of file Simple.f90.
Referenced by euler::flux1d().
subroutine simple::zwxpy (integer(kind=4), intent(in) numDim, integer(kind=8), intent(in) numPoints, integer(kind=8), dimension(numdim), intent(in) bufferSize, integer(kind=8), dimension(2*numdim), intent(in) bufferInterval, real(kind=8), dimension(numpoints), intent(in) W, real(kind=8), dimension(numpoints), intent(in) X, real(kind=8), dimension(numpoints), intent(in) Y, real(kind=8), dimension(numpoints), intent(out) Z)
ZWXPY point-wise operator performing Z = WX + Y, where all are vectors.
Definition at line 594 of file Simple.f90.
subroutine simple::zxdoty (integer(kind=4), intent(in) numDim, integer(kind=8), intent(in) numPoints, integer(kind=8), dimension(numdim), intent(in) bufferSize, integer(kind=8), dimension(2*numdim), intent(in) bufferInterval, integer(kind=4), intent(in) numComponents, real(kind=8), dimension(numpoints*numcomponents), intent(in) X, real(kind=8), dimension(numpoints*numcomponents), intent(in) Y, real(kind=8), dimension(numpoints), intent(out) Z)
ZXDOTY numComponents-vector inner product Z = X * Y.
Definition at line 918 of file Simple.f90.
References assignmentxa().
Referenced by viscid::scalarflux1d(), viscid::strongflux1d(), and metricops::vhatcomponent().
subroutine simple::zxy (integer(kind=4), intent(in) numDim, integer(kind=8), intent(in) numPoints, integer(kind=8), dimension(numdim), intent(in) bufferSize, integer(kind=8), dimension(2*numdim), intent(in) bufferInterval, real(kind=8), dimension(numpoints), intent(in) X, real(kind=8), dimension(numpoints), intent(in) Y, real(kind=8), dimension(numpoints), intent(out) Z)
ZXY point-wise operator performing Z = XY (all vectors) ZXY performs Z = XY where X, Y are each contiguous arrays. Operand arrays are contiguous of size numPoints. The kernel operates on the rectangular interval specified by bufferInterval. The shape of the input and output arrays are specified by bufferSize, which is an numDim - dimensional array that specifies the size in each of numDim dimesions.
Parameters:
numDim - const integer input specifies the number of dimensions of the input and output arrays
numPoints - const 64-bit integer input specifies the total size of the input and output arrays
bufferSize - const 64-bit integer array of size numDim specifies the size of the input and output arrays in each of numDim dimensions
bufferInterval - const 64-bit integer array of size 2 x numDim indicating the rectangular interval in which the kernel should operate; e.g. [ iStart iEnd jStart jEnd ]
X - const double precision input array
Y - const double precision input array
Z - double precision output array
Definition at line 438 of file Simple.f90.
Referenced by euler::flux1d(), metricops::gradijktogradxyz(), euler::scalarflux1d(), viscid::scalarflux1d(), viscid::strongflux1d(), and metricops::vhatcomponent().
subroutine simple::zxym1 (integer(kind=4), intent(in) numDim, integer(kind=8), intent(in) numPoints, integer(kind=8), dimension(numdim), intent(in) bufferSize, integer(kind=8), dimension(2*numdim), intent(in) bufferInterval, real(kind=8), dimension(numpoints), intent(in) X, real(kind=8), dimension(numpoints), intent(in) Y, real(kind=8), dimension(numpoints), intent(out) Z)
ZXYM1 point-wise operator performing Z = X/Y (all vectors)
Definition at line 371 of file Simple.f90.
Author
Generated automatically by Doxygen for JustKernels from the source code.