viscid
NAME
viscid -
SYNOPSIS
Functions/Subroutines
subroutine strongflux1d (numDim, fluxDir, gridSizes, numPoints, opInterval, gridType, gridMetric, tauBuffer, energyBuffer, fluxBuffer)
Compute the curvilinear cartesian viscous fluxes in 1 dimension.
subroutine scalarflux1d (numDim, fluxDir, gridSizes, numPoints, opInterval, gridType, gridMetric, gradScalar, fluxBuffer)
Compute the curvilinear cartesian viscous fluxes in 1 dimension.
Function/Subroutine Documentation
subroutine viscid::scalarflux1d (integer(kind=4), intent(in) numDim, integer(kind=4), intent(in) fluxDir, integer(kind=8), dimension(numdim), intent(in) gridSizes, integer(kind=8), intent(in) numPoints, integer(kind=8), dimension(2*numdim), intent(in) opInterval, integer(kind=4), intent(in) gridType, real(kind=8), dimension(numdim*numdim*numpoints), intent(in), target gridMetric, real(kind=8), dimension(numpoints*numdim), intent(in), target gradScalar, real(kind=8), dimension(numpoints), intent(out) fluxBuffer)
Compute the curvilinear cartesian viscous fluxes in 1 dimension. retains logic to simplify calculations on uniform or stretched cartesian grids
See /ref conserve for theory
Definition at line 173 of file Viscid.f90.
References grid::rectilinear, simple::yax(), simple::zxdoty(), and simple::zxy().
subroutine viscid::strongflux1d (integer(kind=4), intent(in) numDim, integer(kind=4), intent(in) fluxDir, integer(kind=8), dimension(numdim), intent(in) gridSizes, integer(kind=8), intent(in) numPoints, integer(kind=8), dimension(2*numdim), intent(in) opInterval, integer(kind=4), intent(in) gridType, real(kind=8), dimension(numdim*numdim*numpoints), intent(in), target gridMetric, real(kind=8), dimension(numpoints*numdim*(numdim+1)/2), intent(in), target tauBuffer, real(kind=8), dimension(numpoints*numdim), intent(in), target energyBuffer, real(kind=8), dimension(numpoints*(numdim+2)), intent(out), target fluxBuffer)
Compute the curvilinear cartesian viscous fluxes in 1 dimension. retains logic to simplify calculations on uniform or stretched cartesian grids
See /ref conserve for theory
Definition at line 22 of file Viscid.f90.
References simple::assignmentxa(), grid::rectilinear, simple::yax(), simple::ywxpy(), simple::zxdoty(), and simple::zxy().
Author
Generated automatically by Doxygen for JustKernels from the source code.