.TH "WENOKernels.H" 3 "Fri Apr 10 2020" "Version 1.0" "JustKernels" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WENOKernels.H \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'FC\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBFC_MODULE\fP (navierstokesrhsweno, ns_rhs_weno, NAVIERSTOKESRHSWENO, NS_RHS_WENO)(const int *\fBnumDim\fP"
.br
.ti -1c
.RI "void \fBFC_MODULE\fP (navierstokesrhsweno, ns_rhs_muscl, NAVIERSTOKESRHSWENO, NS_RHS_MUSCL)(const int *\fBnumDim\fP"
.br
.ti -1c
.RI "void \fBFC_MODULE\fP (navierstokesrhsweno, ns_bc_weno, NAVIERSTOKESRHSWENO, NS_BC_WENO)(const int *\fBnumDim\fP"
.br
.ti -1c
.RI "void \fBFC_MODULE\fP (navierstokesrhsweno, ns_bc_fixvalue, NAVIERSTOKESRHSWENO, NS_BC_FIXVALUE)(const int *\fBnumDim\fP"
.br
.ti -1c
.RI "void \fBFC_MODULE\fP (navierstokesrhsweno, ns_rhs_axisymmetric, NAVIERSTOKESRHSWENO, NS_RHS_AXISYMMETRIC)(const int *\fBnumDim\fP"
.br
.ti -1c
.RI "void \fBFC_MODULE\fP (navierstokesrhsweno, ns_rhs_axisymmetric_axis, NAVIERSTOKESRHSWENO, NS_RHS_AXISYMMETRIC_AXIS)(const int *\fBnumDim\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "void const size_t * \fBbufferSizes\fP"
.br
.ti -1c
.RI "void const size_t const size_t * \fBnumPointsBuffer\fP"
.br
.ti -1c
.RI "void const size_t const size_t const int * \fBnumScalars\fP"
.br
.ti -1c
.RI "void const size_t const size_t const int const int * \fBnumEquations\fP"
.br
.ti -1c
.RI "void const size_t const size_t const int const int const int * \fBwenoDir\fP"
.br
.ti -1c
.RI "void const size_t const size_t const int const int const int const int * \fBsconn\fP"
.br
.ti -1c
.RI "void const size_t const size_t const int const int const int const int double * \fBdFluxBuffer\fP"
.br
.ti -1c
.RI "void const size_t const size_t const int const int const int const int double const double * \fBinviscidFluxBuffer\fP"
.br
.ti -1c
.RI "void const size_t const size_t const int const int const int const int double const double const size_t * \fBopInterval\fP"
.br
.ti -1c
.RI "void const size_t const size_t const int const int const int const int double const double const size_t const double * \fBgridMetric\fP"
.br
.ti -1c
.RI "void const size_t const size_t const int const int const int const int double const double const size_t const double const double * \fBjacobianDeterminant\fP"
.br
.ti -1c
.RI "void const size_t const size_t const int const int const int const int double const double const size_t const double const double const double * \fBgridCoordinates\fP"
.br
.ti -1c
.RI "void const size_t const size_t const int const int const int const int double const double const size_t const double const double const double const int * \fBgridType\fP"
.br
.ti -1c
.RI "void const size_t const size_t const int const int const int const int double const double const size_t const double const double const double const int const double * \fBrhoBuffer\fP"
.br
.ti -1c
.RI "void const size_t const size_t const int const int const int const int double const double const size_t const double const double const double const int const double const double * \fBrhoVBuffer\fP"
.br
.ti -1c
.RI "void const size_t const size_t const int const int const int const int double const double const size_t const double const double const double const int const double const double const double * \fBrhoEBuffer\fP"
.br
.ti -1c
.RI "void const size_t const size_t const int const int const int const int double const double const size_t const double const double const double const int const double const double const double const double * \fBpressureBuffer\fP"
.br
.ti -1c
.RI "void const size_t const size_t const int const int const int const int double const double const size_t const double const double const double const int const double const double const double const double const double * \fBtemperatureBuffer\fP"
.br
.ti -1c
.RI "void const size_t const size_t const int const int const int const int double const double const size_t const double const double const double const int const double const double const double const double const double const double * \fBsosBuffer\fP"
.br
.ti -1c
.RI "void const size_t const size_t const int const int const int const int double const double const size_t const double const double const double const int const double const double const double const double const double const double const double * \fBscalarBuffer\fP"
.br
.ti -1c
.RI "void const size_t const size_t const int const int const int const int double const double const size_t const double const double const double const int const double const double const double const double const double const double const double const double * \fBwenoAlpha\fP"
.br
.ti -1c
.RI "void const size_t const size_t const int const int const int const int double const double const size_t const double const double const double const int const double const double const double const double const double const double const double const double const int * \fBwenoOptions\fP"
.br
.ti -1c
.RI "void const size_t const size_t const int const int const int const int double const double const size_t const double const double const double const int const double const double const double const double const double const double const double const double const int const size_t * \fBeosInfo\fP"
.br
.ti -1c
.RI "void const size_t const size_t const int const int const int const int double const double const size_t const double const double const double const int const double const double const double const double const double const double const double const double const int const size_t const double * \fBeosNonDimen\fP"
.br
.ti -1c
.RI "void const size_t const size_t const int const int const int const int double const double const size_t const double const double const double const int const double const double const double const double const double const double const double const double const int const size_t const double const double * \fBeosGasParams\fP"
.br
.ti -1c
.RI "void const size_t const size_t const int * \fBdir\fP"
.br
.ti -1c
.RI "void const size_t const size_t const int const int const size_t const size_t * \fBbufferInterval\fP"
.br
.ti -1c
.RI "void const size_t const size_t const int const int const size_t const size_t const int const double const double const double * \fBbcParams\fP"
.br
.ti -1c
.RI "void const size_t const size_t const int const int const size_t const size_t const int const double const double const double const double * \fBgasParams\fP"
.br
.ti -1c
.RI "void const size_t const size_t const int const int const size_t const size_t const int const double const double const double const double const int const double const double const double const double const double const double const double const double * \fBrhoRHSBuffer\fP"
.br
.ti -1c
.RI "void const size_t const size_t const int const int const size_t const size_t const int const double const double const double const double const int const double const double const double const double const double const double const double const double const double * \fBrhoVRHSBuffer\fP"
.br
.ti -1c
.RI "void const size_t const size_t const int const int const size_t const size_t const int const double const double const double const double const int const double const double const double const double const double const double const double const double const double const double * \fBrhoERHSBuffer\fP"
.br
.ti -1c
.RI "void const size_t const size_t const int const int const size_t const size_t const int const double const double const double const double const int const double const double const double const double const double const double const double const double const double const double const double * \fBscalarRHSBuffer\fP"
.br
.ti -1c
.RI "void const size_t const size_t const int const size_t const size_t const int const double const double const double * \fBgridMetric2\fP"
.br
.ti -1c
.RI "void const size_t const size_t const int const size_t const size_t const int const double const double const double const int * \fBbcType\fP"
.br
.ti -1c
.RI "void const size_t const size_t const int const size_t * \fBnumPatchPointsOp\fP"
.br
.ti -1c
.RI "void const size_t const size_t const int const size_t const size_t * \fBpatchPointsOp\fP"
.br
.ti -1c
.RI "void const size_t const size_t const int const size_t const size_t const int const double const double const int const double const double const int const double const double const double const size_t const double * \fBeosNonDim\fP"
.br
.ti -1c
.RI "void const size_t const size_t const int const size_t const size_t const int const double const double const int const double const double const int const double const double const double const size_t const double const double const double * \fBrhoTarget\fP"
.br
.ti -1c
.RI "void const size_t const size_t const int const size_t const size_t const int const double const double const int const double const double const int const double const double const double const size_t const double const double const double const double * \fBrhoVTarget\fP"
.br
.ti -1c
.RI "void const size_t const size_t const int const size_t const size_t const int const double const double const int const double const double const int const double const double const double const size_t const double const double const double const double const double * \fBrhoETarget\fP"
.br
.ti -1c
.RI "void const size_t const size_t const int const size_t const size_t const int const double const double const int const double const double const int const double const double const double const size_t const double const double const double const double const double const double * \fBscalarTarget\fP"
.br
.ti -1c
.RI "void const size_t const size_t const int const int * \fBnormDir\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void FC_MODULE (navierstokesrhsweno, ns_rhs_weno, NAVIERSTOKESRHSWENO, NS_RHS_WENO) const"

.SS "void FC_MODULE (navierstokesrhsweno, ns_rhs_muscl, NAVIERSTOKESRHSWENO, NS_RHS_MUSCL) const"

.SS "void FC_MODULE (navierstokesrhsweno, ns_bc_weno, NAVIERSTOKESRHSWENO, NS_BC_WENO) const"

.SS "void FC_MODULE (navierstokesrhsweno, ns_bc_fixvalue, NAVIERSTOKESRHSWENO, NS_BC_FIXVALUE) const"

.SS "void FC_MODULE (navierstokesrhsweno, ns_rhs_axisymmetric, NAVIERSTOKESRHSWENO, NS_RHS_AXISYMMETRIC) const"

.SS "void FC_MODULE (navierstokesrhsweno, ns_rhs_axisymmetric_axis, NAVIERSTOKESRHSWENO, NS_RHS_AXISYMMETRIC_AXIS) const"

.SH "Variable Documentation"
.PP 
.SS "void const size_t const size_t const int const size_t const size_t const int const double const double const int const double* bcParams"

.PP
Definition at line 22 of file WENOKernels\&.H\&.
.SS "void const size_t const size_t const int const size_t const size_t const int const double const double const int * bcType"

.PP
Definition at line 34 of file WENOKernels\&.H\&.
.SS "void const size_t* bufferInterval"

.PP
Definition at line 22 of file WENOKernels\&.H\&.
.SS "void const size_t* bufferSizes"

.PP
Definition at line 9 of file WENOKernels\&.H\&.
.SS "void const size_t const size_t const int const int const int const int double* dFluxBuffer"

.PP
Definition at line 9 of file WENOKernels\&.H\&.
.SS "void const size_t const size_t const int * dir"

.PP
Definition at line 22 of file WENOKernels\&.H\&.
.SS "void const size_t const size_t const int const size_t const size_t const int const double const double const int const double const double const int const double const double const double const size_t const double const double* eosGasParams"

.PP
Definition at line 9 of file WENOKernels\&.H\&.
.SS "void const size_t const size_t const int const size_t const size_t const int const double const double const int const double const double const int const double const double const double const size_t * eosInfo"

.PP
Definition at line 9 of file WENOKernels\&.H\&.
.SS "void const size_t const size_t const int const size_t const size_t const int const double const double const int const double const double const int const double const double const double const size_t const double* eosNonDim"

.PP
Definition at line 46 of file WENOKernels\&.H\&.
.SS "void const size_t const size_t const int const size_t const size_t const int const double const double const double const int const double const double const int const double const double const double const double const double const double const double const double const double const double const double const size_t const double* eosNonDimen"

.PP
Definition at line 9 of file WENOKernels\&.H\&.
.SS "void const size_t const size_t const int const size_t const size_t const int const double const double const int const double const double* gasParams"

.PP
Definition at line 22 of file WENOKernels\&.H\&.
.SS "void const size_t const size_t const int const int const size_t const double const double const int const double * gridCoordinates"

.PP
Definition at line 9 of file WENOKernels\&.H\&.
.SS "void const size_t const size_t const int const int const size_t const double* gridMetric"

.PP
Definition at line 9 of file WENOKernels\&.H\&.
.SS "void const size_t const size_t const int const size_t const size_t const int const double const double const double* gridMetric2"

.PP
Definition at line 34 of file WENOKernels\&.H\&.
.SS "void const size_t const size_t const int const int const size_t const double const double const int* gridType"

.PP
Definition at line 9 of file WENOKernels\&.H\&.
.SS "void const size_t const size_t const int const int const int const int double const double* inviscidFluxBuffer"

.PP
Definition at line 9 of file WENOKernels\&.H\&.
.SS "void const size_t const size_t const int const int const size_t const double const double* jacobianDeterminant"

.PP
Definition at line 9 of file WENOKernels\&.H\&.
.SS "void const size_t const size_t const int const int* normDir"

.PP
Definition at line 64 of file WENOKernels\&.H\&.
.SS "void const size_t const size_t const int const int* numEquations"

.PP
Definition at line 9 of file WENOKernels\&.H\&.
.SS "void const size_t const size_t const int const size_t* numPatchPointsOp"

.PP
Definition at line 46 of file WENOKernels\&.H\&.
.SS "void const size_t const size_t* numPointsBuffer"

.PP
Definition at line 9 of file WENOKernels\&.H\&.
.SS "void const size_t const size_t const int* numScalars"

.PP
Definition at line 9 of file WENOKernels\&.H\&.
.SS "void const size_t const size_t const int const int const size_t* opInterval"

.PP
Definition at line 9 of file WENOKernels\&.H\&.
.SS "void const size_t const size_t const int const size_t const size_t* patchPointsOp"

.PP
Definition at line 46 of file WENOKernels\&.H\&.
.SS "void const size_t const size_t const int const int const size_t const double const double const int const double const double const double const double const double* pressureBuffer"

.PP
Definition at line 9 of file WENOKernels\&.H\&.
.SS "void const size_t const size_t const int const int const size_t const double const double const int const double const double* rhoBuffer"

.PP
Definition at line 9 of file WENOKernels\&.H\&.
.SS "void const size_t const size_t const int const int const size_t const double const double const int const double const double const double const double* rhoEBuffer"

.PP
Definition at line 9 of file WENOKernels\&.H\&.
.SS "void const size_t const size_t const int const int const size_t const double const double const int const double const double const double const double const double const double double double double * rhoERHSBuffer"

.PP
Definition at line 22 of file WENOKernels\&.H\&.
.SS "void const size_t const size_t const int const size_t const size_t const int const double const double const int const double const double const int const double const double const double const size_t const double const double const double const double const double* rhoETarget"

.PP
Definition at line 46 of file WENOKernels\&.H\&.
.SS "void const size_t const size_t const int const int const size_t const double const double const int const double const double const double const double const double const double double * rhoRHSBuffer"

.PP
Definition at line 22 of file WENOKernels\&.H\&.
.SS "void const size_t const size_t const int const size_t const size_t const int const double const double const int const double const double const int const double const double const double const size_t const double const double const double* rhoTarget"

.PP
Definition at line 46 of file WENOKernels\&.H\&.
.SS "void const size_t const size_t const int const int const size_t const double const double const int const double const double const double* rhoVBuffer"

.PP
Definition at line 9 of file WENOKernels\&.H\&.
.SS "void const size_t const size_t const int const int const size_t const double const double const int const double const double const double const double const double const double double double * rhoVRHSBuffer"

.PP
Definition at line 22 of file WENOKernels\&.H\&.
.SS "void const size_t const size_t const int const size_t const size_t const int const double const double const int const double const double const int const double const double const double const size_t const double const double const double const double* rhoVTarget"

.PP
Definition at line 46 of file WENOKernels\&.H\&.
.SS "void const size_t const size_t const int const int const size_t const double const double const int const double const double const double const double const double const double* scalarBuffer"

.PP
Definition at line 9 of file WENOKernels\&.H\&.
.SS "void const size_t const size_t const int const int const size_t const double const double const int const double const double const double const double const double const double double double double double * scalarRHSBuffer"

.PP
Definition at line 22 of file WENOKernels\&.H\&.
.SS "void const size_t const size_t const int const size_t const size_t const int const double const double const int const double const double const int const double const double const double const size_t const double const double const double const double const double const double* scalarTarget"

.PP
Definition at line 46 of file WENOKernels\&.H\&.
.SS "void const size_t const size_t const int const int* sconn"

.PP
Definition at line 9 of file WENOKernels\&.H\&.
.SS "void const size_t const size_t const int const size_t const size_t const int const double const double const int const double const double const int const double * sosBuffer"

.PP
Definition at line 9 of file WENOKernels\&.H\&.
.SS "void const size_t const size_t const int const size_t const size_t const int const double const double const int const double const double const int const double const double const double * temperatureBuffer"

.PP
Definition at line 9 of file WENOKernels\&.H\&.
.SS "void const size_t const size_t const int const int const size_t const size_t const int const double const double const double const double const int const double const double const double const double const double const double const double const double const double const double const double const double * wenoAlpha"

.PP
Definition at line 9 of file WENOKernels\&.H\&.
.SS "void const size_t const size_t const int const int const int* wenoDir"

.PP
Definition at line 9 of file WENOKernels\&.H\&.
.SS "void const size_t const size_t const int const int const size_t const size_t const int const double const double const double const double const int const double const double const double const double const double const double const double const double const double const double const double const double const int * wenoOptions"

.PP
Definition at line 9 of file WENOKernels\&.H\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for JustKernels from the source code\&.
