name: CI

on:
  pull_request:
  push:
    branches: main
  schedule:
  - cron:  '5 0 * * *'


jobs:

    examples_lassen:
        name: examples-on-lassen
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        - name: Examples result
          run: |
             . .ci-support/check-test-result.sh lassen mirgecom-examples
