name: CI

on:
  pull_request:
  push:
    branches: main
  schedule:
  - cron:  '5 0 * * *'


jobs:

    mirgecom_lassen:
        name: mirgecom-on-lassen
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        - name: testing-ouput
          run: |
             .ci-support/get-package-testing-log.sh lassen mirgecom
        - name: examples
          run: |
             .ci-support/check-test-result.sh lassen mirgecom mirgecom-examples

    isolator_lassen:
        name: isolator-on-lassen
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        - name: testing-output
          run: |
             .ci-support/get-package-testing-log.sh lassen isolator
        - name: Serial isolator-3d-mixture
          run: |
             .ci-support/check-test-result.sh lassen isolator serial-3d-combustion
        # - name: Parallel2 injection-3d-combustion
        #  run: |
        #     .ci-support/check-test-result.sh lassen parallel2-injection-3d
        # - name: Parallel4 injection-3d-combustion
        #  run: |
        #     .ci-support/check-test-result.sh lassen parallel4-injection-3d
