name: isolator-nightly-quartz

on:
  pull_request:
  push:
    branches: main
  schedule:
  - cron:  '5 0 * * *'


jobs:

    isolator:
        name: isolator-tests
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        - name: testing-output
          run: |
             .ci-support/get-package-testing-log.sh quartz isolator
        - name: Serial isolator-3d-mixture
          run: |
             .ci-support/check-test-result.sh quartz isolator serial-3d-combustion
        - name: parallel (2) injection-3d-combustion
          run: |
             .ci-support/check-test-result.sh quartz isolator parallel-3d-combustion_2
        - name: parallel (4) injection-3d-combustion
          run: |
             .ci-support/check-test-result.sh quartz isolator parallel-3d-combustion_4