name: mirgecom-nightly-quartz

on:
  pull_request:
  push:
    branches: main
  schedule:
  - cron:  '5 0 * * *'


jobs:

    mirgecom-examples:
        name: mirgecom-examples
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        - name: testing-ouput
          run: |
             .ci-support/get-package-testing-log.sh quartz mirgecom
        - name: examples
          run: |
             .ci-support/check-test-result.sh quartz mirgecom mirgecom-examples
